<?php

namespace Modules\FinTech\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\FinTech\Models\Category;
use Modules\FinTech\Enums\CategoryType;
use Illuminate\Support\Facades\DB;

class CategorySeeder extends Seeder
{
  protected array $categories = [];

  public function run(): void
  {
    $this->prepareCategories();
    $this->seedCategories();
  }

  /**
  * Siapkan semua data kategori dalam array.
  */
  protected function prepareCategories(): void
  {
    $this->categories = [
      // ========== EXPENSE ==========
      [
        'name' => 'Makanan & Minuman',
        'type' => CategoryType::EXPENSE,
        'icon' => 'bi-cup-hot',
        'color' => '#FF6384',
        // Merah muda cerah – menggugah selera
        'keywords' => ['restoran',
          'rm ',
          'warung',
          'kafe',
          'cafe',
          'coffee',
          'mcd',
          'kfc',
          'pizza',
          'burger',
          'sushi',
          'steak',
          'martabak',
          'bakso',
          'sate',
          'nasi goreng',
          'mie ayam',
          'gado-gado',
          'sarapan',
          'makan siang',
          'makan malam',
          'minum',
          'kopi',
          'teh',
          'jus',
          'es',
          'gofood',
          'grabfood',
          'shopeefood',
          'food',
          'kuliner',
          'catering',
          'kantin',
          'snack',
          'cemilan',
          'roti',
          'kue',
          'cokelat',
          'es krim',
          'ice cream',
          'boba',
          'starbucks',
          'hokben',
          'solaria',
          'wendy',
          'a&w',
          'dunkin',
          'jco'],
        'metadata' => ['tags' => ['kebutuhan_pokok',
          'harian']],
        'children' => [
          ['name' => 'Makanan',
            'icon' => 'bi-egg-fried',
            'color' => '#FF6384',
            'keywords' => ['makan',
              'nasi',
              'lauk',
              'sayur',
              'resto',
              'restaurant',
              'restoran',
              'rm',
              'warung makan',
              'warteg',
              'prasmanan']],
          ['name' => 'Minuman',
            'icon' => 'bi-cup',
            'color' => '#FF9F40',
            'keywords' => ['minum',
              'kopi',
              'teh',
              'jus',
              'es',
              'boba',
              'bubble tea',
              'soda',
              'air mineral',
              'starbucks',
              'chatime',
              'kopi kenangan',
              'janji jiwa',
              'fore coffee']],
          ['name' => 'Makan di Luar',
            'icon' => 'bi-shop',
            'color' => '#FFCE56',
            'keywords' => ['restoran',
              'cafe',
              'kafe',
              'dine in',
              'dine out',
              'makan malam romantis',
              'steak',
              'sushi',
              'all you can eat',
              'buffet',
              'fine dining']],
        ]
      ],
      [
        'name' => 'Transportasi',
        'type' => CategoryType::EXPENSE,
        'icon' => 'bi-car-front',
        'color' => '#36A2EB',
        // Biru cerah – melambangkan mobilitas
        'keywords' => ['transport',
          'transportasi',
          'bensin',
          'pertamina',
          'shell',
          'bp',
          'vivo',
          'spbu',
          'bbm',
          'bahan bakar',
          'parkir',
          'tol',
          'e-toll',
          'flazz',
          'brizzi',
          'gojek',
          'grab',
          'maxim',
          'ojek',
          'taksi',
          'blue bird',
          'bus',
          'kereta',
          'commuter line',
          'krl',
          'mrt',
          'lrt',
          'transjakarta',
          'tj',
          'damri',
          'travel',
          'tiket pesawat',
          'garuda',
          'lion air',
          'citilink',
          'air asia',
          'refund tiket'],
        'metadata' => ['tags' => ['kebutuhan_pokok',
          'mobilitas']],
        'children' => [
          ['name' => 'Bahan Bakar',
            'icon' => 'bi-fuel-pump',
            'color' => '#4BC0C0',
            'keywords' => ['bensin',
              'pertamax',
              'pertalite',
              'dex',
              'solar',
              'spbu',
              'bbm',
              'fuel',
              'shell',
              'bp',
              'vivo',
              'pengisian',
              'isi bensin']],
          ['name' => 'Transportasi Umum',
            'icon' => 'bi-bus-front',
            'color' => '#9966FF',
            'keywords' => ['bus',
              'kereta',
              'krl',
              'commuter',
              'mrt',
              'lrt',
              'transjakarta',
              'tj',
              'damri',
              'angkot',
              'angkutan',
              'tiket kereta',
              'tiket bus']],
          ['name' => 'Ojek Online / Taksi',
            'icon' => 'bi-bicycle',
            'color' => '#FF8C00',
            'keywords' => ['gojek',
              'grab',
              'maxim',
              'ojol',
              'ojek',
              'goride',
              'gocar',
              'grabbike',
              'taksi',
              'blue bird',
              'express',
              'silver bird',
              'taksi online']],
          ['name' => 'Parkir & Tol',
            'icon' => 'bi-p-circle',
            'color' => '#8AC24A',
            'keywords' => ['parkir',
              'parking',
              'tol',
              'e-toll',
              'flazz',
              'brizzi',
              'jalan tol',
              'jasa marga',
              'rest area']],
          ['name' => 'Tarik Tunai',
            'icon' => 'bi-cash',
            'color' => '#DC143C',
            'keywords' => ['tarik tunai',
              'penarikan tunai',
              'atm',
              'cardless',
              'tarik tunai di atm',
              'tarik tunai cardless',
              'tarik tunai tanpa kartu',
              'penarikan tunai di atm',
              'tarik tunai kartu',
              'tarik tunai di atm link']],
        ]
      ],
      [
        'name' => 'Belanja',
        'type' => CategoryType::EXPENSE,
        'icon' => 'bi-cart',
        'color' => '#FFD700',
        // Emas – identik dengan belanja
        'keywords' => ['belanja',
          'shopping',
          'mall',
          'plaza',
          'supermarket',
          'minimarket',
          'indomaret',
          'alfamart',
          'alfamidi',
          'circle k',
          'lawson',
          'family mart',
          'transmart',
          'carrefour',
          'hypermart',
          'giant',
          'lotte mart',
          'aeon',
          'toko',
          'shopee',
          'tokopedia',
          'lazada',
          'blibli',
          'bukalapak',
          'amazon',
          'e-commerce',
          'online shop'],
        'metadata' => ['tags' => ['sekunder']],
        'children' => [
          ['name' => 'Kebutuhan Rumah Tangga',
            'icon' => 'bi-house',
            'color' => '#4DB6AC',
            'keywords' => ['sembako',
              'beras',
              'minyak goreng',
              'gula',
              'garam',
              'tepung',
              'telur',
              'susu',
              'roti',
              'sabun',
              'deterjen',
              'pembersih',
              'tisu',
              'popok',
              'kebutuhan rumah',
              'perlengkapan rumah',
              'alat dapur',
              'perabot']],
          ['name' => 'Pakaian',
            'icon' => 'bi-bag',
            'color' => '#F06292',
            'keywords' => ['baju',
              'celana',
              'sepatu',
              'sandal',
              'tas',
              'dompet',
              'aksesoris',
              'fashion',
              'pakaian',
              'kaos',
              'kemeja',
              'dress',
              'rok',
              'jaket',
              'h&m',
              'uniqlo',
              'zara',
              'mango',
              'pull&bear',
              'stradivarius',
              'bershka']],
          ['name' => 'Elektronik & Gadget',
            'icon' => 'bi-laptop',
            'color' => '#7986CB',
            'keywords' => ['hp',
              'handphone',
              'smartphone',
              'laptop',
              'komputer',
              'tablet',
              'ipad',
              'iphone',
              'samsung',
              'xiaomi',
              'oppo',
              'vivo',
              'realme',
              'macbook',
              'elektronik',
              'gadget',
              'aksesoris hp',
              'charger',
              'headset',
              'earphone']],
          ['name' => 'E-Wallet',
            'icon' => 'bi-wallet2',
            'color' => '#20B2AA',
            'keywords' => ['gopay',
              'shopeepay',
              'ovo',
              'dana',
              'linkaja',
              'ipaymu',
              'doku',
              'pembayaran gopay customer',
              'pembayaran shopee pay',
              'pembayaran shopee indonesia',
              'pembayaran ovo',
              'pembayaran danatopup',
              'pembayaran tokopedia',
              'pembayaran ipaymu',
              'pembayaran doku va',
              'qr pay',
              'qris',
              'transfer ke espay debit indonesia',
              'pembayaran qr',
              'transfer ke airpay international indonesia',
              'transfer ke gopay',
              'transfer ke shopee pay',
              'transfer ke ovo']],
        ]
      ],
      [
        'name' => 'Tagihan & Utilitas',
        'type' => CategoryType::EXPENSE,
        'icon' => 'bi-receipt',
        'color' => '#2E8B57',
        // Hijau laut – stabil dan rutin
        'keywords' => ['tagihan',
          'bill',
          'pln',
          'listrik',
          'pdam',
          'air',
          'pgn',
          'gas',
          'internet',
          'wifi',
          'indihome',
          'first media',
          'biznet',
          'myrepublic',
          'pulsa',
          'telkomsel',
          'xl',
          'indosat',
          'tri',
          'smartfren',
          'axis',
          'paket data',
          'kuota',
          'bpjs',
          'asuransi',
          'premi',
          'sewa',
          'kontrakan',
          'kost',
          'kos',
          'apartemen',
          'rumah',
          'cicilan',
          'kpr',
          'leasing'],
        'metadata' => ['tags' => ['kebutuhan_pokok',
          'rutin']],
        'children' => [
          ['name' => 'Listrik',
            'icon' => 'bi-lightning',
            'color' => '#FFCE56',
            'keywords' => ['pln',
              'listrik',
              'token listrik',
              'prabayar',
              'pascabayar',
              'pembayaran pln prabayar']],
          ['name' => 'Air',
            'icon' => 'bi-droplet',
            'color' => '#00BFFF',
            'keywords' => ['pdam',
              'air',
              'pam',
              'palang',
              'palapa']],
          ['name' => 'Internet & Pulsa',
            'icon' => 'bi-wifi',
            'color' => '#9370DB',
            'keywords' => ['internet',
              'wifi',
              'indihome',
              'first media',
              'biznet',
              'myrepublic',
              'telkom',
              'indihome',
              'pembayaran telkom/indihome']],
          ['name' => 'Pulsa',
            'icon' => 'bi-phone',
            'color' => '#00CED1',
            'keywords' => ['pulsa',
              'telkomsel',
              'xl',
              'indosat',
              'tri',
              'smartfren',
              'axis',
              'im3',
              'ooredoo',
              'prepaid',
              'pascabayar',
              'paket data',
              'kuota',
              'pembayaran telkomsel prepaid',
              'pembayaran im3 ooredoo',
              'pembayaran 3 prepaid',
              'pembayaran xl axiata',
              'trf/pay/top-up echannel kartu']],
          ['name' => 'Sewa / KPR',
            'icon' => 'bi-building',
            'color' => '#FF6347',
            'keywords' => ['sewa',
              'kontrakan',
              'kost',
              'kos',
              'apartemen',
              'rumah',
              'kpr',
              'cicilan rumah',
              'angsuran',
              'pembayaran sewa',
              'rent',
              'sewa kontrakan',
              'uang sewa rumah',
              'bayar kontrakan',
              'iuran komplek']],
        ]
      ],
      [
        'name' => 'Hiburan',
        'type' => CategoryType::EXPENSE,
        'icon' => 'bi-film',
        'color' => '#8A2BE2',
        // Ungu – menyenangkan dan kreatif
        'keywords' => ['hiburan',
          'entertainment',
          'bioskop',
          'cinema',
          'xxi',
          'cgv',
          'cinepolis',
          'netflix',
          'spotify',
          'youtube',
          'disney',
          'hbo',
          'vidio',
          'viki',
          'iqiyi',
          'we tv',
          'langganan',
          'subscription',
          'game',
          'steam',
          'playstation',
          'nintendo',
          'xbox',
          'mobile legend',
          'pubg',
          'free fire',
          'genshin',
          'konser',
          'event',
          'tiket',
          'pertunjukan',
          'teater',
          'museum',
          'wisata'],
        'metadata' => ['tags' => ['tersier',
          'non-esensial']],
        'children' => [
          ['name' => 'Streaming & Langganan',
            'icon' => 'bi-play-circle',
            'color' => '#FF4500',
            'keywords' => ['netflix',
              'spotify',
              'youtube premium',
              'disney+',
              'hbo go',
              'vidio',
              'viki',
              'iqiyi',
              'we tv',
              'langganan',
              'subscription']],
          ['name' => 'Bioskop & Acara',
            'icon' => 'bi-ticket-perforated',
            'color' => '#F06292',
            'keywords' => ['bioskop',
              'cinema',
              'xxi',
              'cgv',
              'cinepolis',
              'tiket',
              'nonton',
              'konser',
              'event',
              'pertunjukan',
              'teater',
              'stand up',
              'comedy']],
          ['name' => 'Game',
            'icon' => 'bi-controller',
            'color' => '#6A5ACD',
            'keywords' => ['game',
              'steam',
              'playstation',
              'psn',
              'nintendo',
              'xbox',
              'game pass',
              'mobile legend',
              'pubg',
              'free fire',
              'genshin impact',
              'valorant',
              'top up',
              'diamond',
              'uc',
              'skin',
              'item game',
              'dlc']],
        ]
      ],
      [
        'name' => 'Kesehatan',
        'type' => CategoryType::EXPENSE,
        'icon' => 'bi-heart-pulse',
        'color' => '#FF7F50',
        // Coral – hangat dan peduli
        'keywords' => ['kesehatan',
          'health',
          'dokter',
          'rumah sakit',
          'klinik',
          'puskesmas',
          'obat',
          'apotek',
          'farmasi',
          'vitamin',
          'suplemen',
          'bpjs kesehatan',
          'asuransi kesehatan',
          'medical',
          'check up',
          'laboratorium',
          'rontgen',
          'gigi',
          'dokter gigi',
          'behel',
          'kacamata',
          'softlens',
          'optik'],
        'metadata' => ['tags' => ['kebutuhan_pokok',
          'darurat']],
        'children' => [
          ['name' => 'Obat & Vitamin',
            'icon' => 'bi-capsule',
            'color' => '#3CB371',
            'keywords' => ['obat',
              'vitamin',
              'suplemen',
              'apotek',
              'kimia farma',
              'century',
              'guardian',
              'watson',
              'obat resep',
              'obat bebas']],
          ['name' => 'Dokter & Rumah Sakit',
            'icon' => 'bi-hospital',
            'color' => '#FF1493',
            'keywords' => ['dokter',
              'rumah sakit',
              'rs ',
              'klinik',
              'puskesmas',
              'ugd',
              'igd',
              'rawat inap',
              'operasi',
              'bedah',
              'poli',
              'spesialis']],
        ]
      ],
      [
        'name' => 'Pendidikan',
        'type' => CategoryType::EXPENSE,
        'icon' => 'bi-book',
        'color' => '#556B2F',
        // Hijau zaitun gelap – serius dan intelek
        'keywords' => ['pendidikan',
          'education',
          'sekolah',
          'kuliah',
          'universitas',
          'spp',
          'uang pangkal',
          'biaya pendidikan',
          'kursus',
          'les',
          'bimbel',
          'ruang guru',
          'zenius',
          'pijar',
          'buku',
          'alat tulis',
          'stationery',
          'seminar',
          'workshop',
          'pelatihan',
          'training',
          'sertifikasi',
          'bootcamp',
          'online course',
          'udemy',
          'coursera',
          'dicoding',
          'harisenin',
          'revou'],
        'metadata' => ['tags' => ['investasi',
          'sekunder']],
        'children' => [
          ['name' => 'Kursus & Pelatihan',
            'icon' => 'bi-mortarboard',
            'color' => '#008B8B',
            'keywords' => ['kursus',
              'les',
              'bimbel',
              'pelatihan',
              'training',
              'sertifikasi',
              'bootcamp',
              'online course',
              'udemy',
              'coursera',
              'dicoding']],
          ['name' => 'Buku & Materi',
            'icon' => 'bi-journal',
            'color' => '#4169E1',
            'keywords' => ['buku',
              'novel',
              'komik',
              'majalah',
              'ebook',
              'kindle',
              'gramedia',
              'periplus',
              'alat tulis',
              'stationery',
              'pensil',
              'pulpen',
              'binder']],
        ]
      ],
      [
        'name' => 'Transfer & Keuangan',
        'type' => CategoryType::EXPENSE,
        'icon' => 'bi-arrow-left-right',
        'color' => '#708090',
        'keywords' => ['transfer',
          'trsf',
          'bi fast',
          'kliring',
          'rtgs',
          'skn',
          'antar bank',
          'biaya admin',
          'administrasi',
          'admin bank',
          'biaya transfer',
          'pajak',
          'bunga',
          'denda',
          'penalty',
          'fee'],
        'metadata' => ['tags' => ['transfer',
          'keuangan']],
        'children' => [
          ['name' => 'Biaya Admin & Pajak',
            'icon' => 'bi-calculator',
            'color' => '#6c757d',
            'keywords' => ['biaya admin',
              'administrasi',
              'admin bank',
              'biaya transfer',
              'pajak',
              'pph',
              'ppn',
              'bunga',
              'denda',
              'penalty',
              'fee',
              'biaya',
              'biaya transaksi',
              'biaya pembayaran',
              'biaya layanan',
              'biaya administrasi rekening',
              'biaya administrasi kartu debit',
              'biaya administrasi kartu kredit',
              'biaya transfer bi fast',
              'by trx bifast',
              'biaya transfer',
              'biaya pembayaran telkomsel prepaid',
              'biaya pembayaran pln prabayar',
              'biaya pembayaran gopay customer',
              'biaya pembayaran shopee pay',
              'biaya pembayaran im3 ooredoo',
              'biaya pembayaran xl axiata',
              'biaya pembayaran 3 prepaid',
              'biaya penarikan tunai di atm link',
              'biaya penggantian kartu atm',
              'biaya saldo minimum',
              'pendebitan otomatis',
              'pembayaran kartu kredit',
              'biaya admin (gopay)',
              'biaya admin gopay']],
          ['name' => 'Transfer Keluar',
            'icon' => 'bi-arrow-right-circle',
            'color' => '#CD853F',
            'keywords' => ['transfer ke',
              'trsf ke',
              'kirim uang',
              'transfer keluar',
              'bayar hutang',
              'bayar utang',
              'pinjaman',
              'pinjem',
              'nafkah istri',
              'uang istri',
              'transfer istri',
              'kirim mertua',
              'kirim orang tua',
              'bayar arisan',
              'iuran',
              'kas bulanan',
              'teman pinjem',
              'teman pinjam',
              'transfer ke bank',
              'trf/pay/top-up echannel kartu',
              'transfer ke bri',
              'transfer ke bsi',
              'transfer ke bca',
              'transfer ke mandiri']],
        ]
      ],
      [
        'name' => 'Lainnya',
        'type' => CategoryType::EXPENSE,
        'icon' => 'bi-three-dots',
        'color' => '#A9A9A9',
        // Abu‑abu gelap
        'keywords' => ['lainnya',
          'other',
          'uncategorized'],
        'metadata' => ['tags' => ['tidak_terkategori']],
      ],

      // ========== INCOME ==========
      [
        'name' => 'Pendapatan Utama',
        'type' => CategoryType::INCOME,
        'icon' => 'bi-cash-stack',
        'color' => '#66CDAA',
        // Aquamarine medium – segar dan positif
        'keywords' => ['gaji',
          'salary',
          'upah',
          'wage',
          'honor',
          'honorarium',
          'tunjangan',
          'bonus',
          'insentif',
          'thr',
          'lembur',
          'overtime',
          'pensiun',
          'pension'],
        'metadata' => ['tags' => ['gaji',
          'rutin',
          'primer']],
        'children' => [
          ['name' => 'Gaji',
            'icon' => 'bi-briefcase',
            'color' => '#1E90FF',
            'keywords' => ['gaji',
              'salary',
              'payroll',
              'gajian',
              'upah',
              'wage',
              'gaji januari',
              'gaji februari',
              'gaji maret',
              'gaji april',
              'gaji mei',
              'gaji juni',
              'gaji juli',
              'gaji agustus',
              'gaji september',
              'gaji oktober',
              'gaji november',
              'gaji desember',
              'uang gaji',
              'trf gaji',
              'transfer gaji']],
          ['name' => 'Bonus & THR',
            'icon' => 'bi-gift',
            'color' => '#FFD700',
            'keywords' => ['bonus',
              'insentif',
              'thr',
              'tunjangan hari raya',
              'reward',
              'komisi']],
          ['name' => 'Uang Cuti',
            'icon' => 'bi-calendar-heart',
            'color' => '#FFA500',
            'keywords' => ['uang cuti',
              'uang perjalanan cuti',
              'cuti']],
        ]
      ],
      [
        'name' => 'Investasi',
        'type' => CategoryType::INCOME,
        'icon' => 'bi-graph-up',
        'color' => '#C71585',
        // Merah‑violet – berani dan menguntungkan
        'keywords' => ['investasi',
          'investment',
          'dividen',
          'dividend',
          'saham',
          'stock',
          'reksadana',
          'mutual fund',
          'obligasi',
          'bond',
          'deposito',
          'bunga',
          'kripto',
          'crypto',
          'bitcoin',
          'ethereum',
          'forex',
          'trading',
          'profit'],
        'metadata' => ['tags' => ['pasif',
          'modal']],
        'children' => [
          ['name' => 'Dividen',
            'icon' => 'bi-pie-chart',
            'color' => '#BA55D3',
            'keywords' => ['dividen',
              'dividend',
              'pembagian laba']],
          ['name' => 'Bunga Deposito',
            'icon' => 'bi-bank',
            'color' => '#9ACD32',
            'keywords' => ['bunga',
              'deposito',
              'interest',
              'tabungan']],
        ]
      ],
      [
        'name' => 'Pendapatan Sampingan',
        'type' => CategoryType::INCOME,
        'icon' => 'bi-brush',
        'color' => '#FF8C00',
        // Oranye gelap – kreatif dan fleksibel
        'keywords' => ['freelance',
          'side hustle',
          'sampingan',
          'proyek',
          'project',
          'jasa',
          'service',
          'konsultan',
          'desain',
          'nulis',
          'fotografi',
          'videografi',
          'editing',
          'ngajar',
          'private',
          'tutor'],
        'metadata' => ['tags' => ['freelance',
          'tidak_tetap']],
      ],
      [
        'name' => 'Hadiah & Transfer Masuk',
        'type' => CategoryType::INCOME,
        'icon' => 'bi-gift-fill',
        'color' => '#FF69B4',
        // Pink panas – menyenangkan
        'keywords' => ['hadiah',
          'gift',
          'transfer masuk',
          'incoming transfer',
          'uang saku',
          'allowance',
          'kiriman',
          'remittance',
          'pemberian',
          'angpao',
          'amplop'],
        'metadata' => ['tags' => ['insidental']],
        'children' => [
          ['name' => 'Transfer Masuk',
            'icon' => 'bi-arrow-left-circle',
            'color' => '#40E0D0',
            'keywords' => ['transfer dari',
              'trsf dari',
              'transfer masuk',
              'incoming transfer',
              'dari shopee',
              'dari airpay',
              'dari modal',
              'teman bayar hutang',
              'bayar hutang',
              'pinjem uang',
              'pinjaman',
              'refund',
              'uang tiket refund',
              'kembalian']],
        ]
      ],
      [
        'name' => 'Lainnya (Pemasukan)',
        'type' => CategoryType::INCOME,
        'icon' => 'bi-three-dots',
        'color' => '#808080',
        // Abu‑abu
        'keywords' => ['lainnya',
          'other',
          'uncategorized income'],
        'metadata' => ['tags' => ['tidak_terkategori']],
      ],

      // ========== BOTH ==========
      [
        'name' => 'Transfer Internal',
        'type' => CategoryType::BOTH,
        'icon' => 'bi-arrow-left-right',
        'color' => '#008080',
        // Teal
        'keywords' => ['transfer antar dompet',
          'internal transfer'],
        'metadata' => ['tags' => ['transfer',
          'internal']],
      ],
    ];
  }

  /**
  * Seed categories dengan efisien.
  */
  protected function seedCategories(): void
  {
    // 1. Seed semua parent terlebih dahulu
    $parents = [];
    foreach ($this->categories as $cat) {
      $children = $cat['children'] ?? [];
      unset($cat['children']);
      $cat['metadata'] = json_encode($cat['metadata'] ?? []);
      $cat['keywords'] = json_encode($cat['keywords'] ?? []);
      $parents[] = $cat;
    }

    // Upsert parents
    foreach (array_chunk($parents, 50) as $chunk) {
      Category::upsert($chunk, ['name', 'type'], ['icon', 'color', 'metadata', 'keywords']);
    }

    // 2. Seed children dengan parent_id
    $childrenData = [];
    foreach ($this->categories as $cat) {
      if (empty($cat['children'])) continue;

      $parent = Category::where('name', $cat['name'])
      ->where('type', $cat['type'])
      ->first();

      if (!$parent) continue;

      foreach ($cat['children'] as $child) {
        $child['parent_id'] = $parent->id;
        $child['type'] = $cat['type'];
        $child['is_system'] = true;
        $child['metadata'] = json_encode($child['metadata'] ?? []);
        $child['keywords'] = json_encode($child['keywords'] ?? []);
        $childrenData[] = $child;
      }
    }

    // Upsert children
    foreach (array_chunk($childrenData, 50) as $chunk) {
      Category::upsert($chunk, ['name', 'type', 'parent_id'], ['icon', 'color', 'metadata', 'keywords']);
    }
  }
}