<?php

namespace Modules\FinTech\Services\Google\Writers;

use Google\Service\Sheets\Request as SheetsRequest;
use Modules\FinTech\Services\Google\SheetCursor;

class FooterWriter
{
  public function __construct(
    protected ValueWriter $valueWriter,
    protected StyleBuilder $styleBuilder
  ) {}

  public function writeFooter(
    string $sheetName,
    SheetCursor $cursor,
    array $headers,
    int $sheetId
  ): void {
    $text = 'Generated by ' . config('app.name', 'Laravel') . ' App - ' . now()->setTimezone(config('app.timezone'))->format('d M Y H:i');
    $emptyRow = array_fill(0, count($headers), '');
    $emptyRow[0] = $text;

    $range = $sheetName . '!A' . $cursor->row;
    $this->valueWriter->queue($range, [$emptyRow]);

    $this->styleBuilder->addRequest(new SheetsRequest([
      'mergeCells' => [
        'range' => [
          'sheetId' => $sheetId,
          'startRowIndex' => $cursor->row - 1,
          'endRowIndex' => $cursor->row,
          'startColumnIndex' => 0,
          'endColumnIndex' => count($headers),
        ],
        'mergeType' => 'MERGE_ALL',
      ],
    ]));
    $this->styleBuilder->addRequest(new SheetsRequest([
      'repeatCell' => [
        'range' => [
          'sheetId' => $sheetId,
          'startRowIndex' => $cursor->row - 1,
          'endRowIndex' => $cursor->row,
          'startColumnIndex' => 0,
          'endColumnIndex' => count($headers),
        ],
        'cell' => ['userEnteredFormat' => [
          'textFormat' => ['italic' => true, 'foregroundColor' => ['red' => 136/255, 'green' => 136/255, 'blue' => 136/255], 'fontSize' => 10],
          'horizontalAlignment' => 'CENTER',
        ]],
        'fields' => 'userEnteredFormat(textFormat,horizontalAlignment)',
      ],
    ]));
    $cursor->advanceRow();
  }
}