<?php

namespace Modules\FinTech\Exports;

use Maatwebsite\Excel\Concerns\ {
  FromArray,
  WithHeadings,
  WithStyles,
  ShouldAutoSize,
  WithEvents,
  WithTitle
};
use Maatwebsite\Excel\Events\AfterSheet;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;
use PhpOffice\PhpSpreadsheet\Style\ {
  Border,
  Fill,
  Font,
  Alignment
};

class DataExport implements FromArray, WithHeadings, WithStyles, ShouldAutoSize, WithEvents, WithTitle
{
  protected string $type;
  protected array $data;

  public function __construct(string $type, array $data) {
    $this->type = $type;
    $this->data = $data;
  }

  /**
  * Data yang akan diekspor.
  */
  public function array(): array
  {
    return $this->data;
  }

  /**
  * Judul kolom diambil dari key array pertama.
  */
  public function headings(): array
  {
    if (empty($this->data)) return [];
    return array_keys($this->data[0]);
  }

  /**
  * Nama sheet.
  */
  public function title(): string
  {
    return match ($this->type) {
      'transactions' => 'Transaksi',
      'transfers' => 'Transfer',
      'budgets' => 'Budget',
      default => 'Data'
      };
    }

    /**
    * Style header dan border data.
    */
    public function styles(Worksheet $sheet) {
      // Tentukan range header
      $highestColumn = $sheet->getHighestColumn();
      $headerRange = 'A1:' . $highestColumn . '1';

      // Style header: bold, putih, background biru, border
      $sheet->getStyle($headerRange)->applyFromArray([
        'font' => [
          'bold' => true,
          'color' => ['rgb' => 'FFFFFF'],
        ],
        'fill' => [
          'fillType' => Fill::FILL_SOLID,
          'startColor' => ['rgb' => '4F81BD'], // biru profesional
        ],
        'borders' => [
          'allBorders' => [
            'borderStyle' => Border::BORDER_THIN,
            'color' => ['rgb' => '000000'],
          ],
        ],
        'alignment' => [
          'horizontal' => Alignment::HORIZONTAL_CENTER,
          'vertical' => Alignment::VERTICAL_CENTER,
        ],
      ]);

      // Border untuk semua sel data
      $dataRowCount = count($this->data);
      if ($dataRowCount > 0) {
        $lastRow = $dataRowCount + 1;
        $dataRange = 'A2:' . $highestColumn . $lastRow;
        $sheet->getStyle($dataRange)->applyFromArray([
          'borders' => [
            'allBorders' => [
              'borderStyle' => Border::BORDER_THIN,
              'color' => ['rgb' => '000000'],
            ],
          ],
        ]);
      }
    }

    /**
    * Tambahkan footer di bawah data.
    */
    public function registerEvents(): array
    {
      return [
        AfterSheet::class => function (AfterSheet $event) {
          $sheet = $event->sheet->getDelegate();
          $row = count($this->data) + 2; // baris setelah data

          // Footer: informasi generate
          $sheet->setCellValue(
            'A' . $row,
            'Generated by VickyServer App - ' . now()->format('d M Y H:i')
          );
          // Merge sampai 5 kolom (cukup untuk kebanyakan tipe)
          $sheet->mergeCells('A' . $row . ':E' . $row);
          $sheet->getStyle('A' . $row)->applyFromArray([
            'font' => [
              'italic' => true,
              'color' => ['rgb' => '888888'],
              'size' => 10,
            ],
            'alignment' => ['horizontal' => Alignment::HORIZONTAL_RIGHT],
          ]);
        },
      ];
    }
  }