<?php

namespace Modules\FinTech\Exports;

use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithStyles;
use Maatwebsite\Excel\Concerns\ShouldAutoSize;
use Maatwebsite\Excel\Concerns\WithEvents;
use Maatwebsite\Excel\Concerns\WithTitle;
use Maatwebsite\Excel\Events\AfterSheet;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\Font;
use PhpOffice\PhpSpreadsheet\Style\Alignment;

class DataExport implements WithHeadings, WithStyles, ShouldAutoSize, WithEvents, WithTitle
{
  protected string $type;
  protected array $data;
  protected array $summary;

  public function __construct(string $type, array $data, array $summary) {
    $this->type = $type;
    $this->data = $data;
    $this->summary = $summary;
  }

  public function headings(): array
  {
    if (empty($this->data)) return [];
    // Dummy, akan ditulis manual di AfterSheet
    return [[]];
  }

  public function title(): string
  {
    return match ($this->type) {
      'transactions' => 'Transaksi',
      'transfers' => 'Transfer',
      'budgets' => 'Budget',
      default => 'Data'
      };
    }

    public function styles(Worksheet $sheet) {
      // Style manual di AfterSheet
    }

    public function registerEvents(): array
    {
      return [
        AfterSheet::class => function (AfterSheet $event) {
          $sheet = $event->sheet->getDelegate();
          $metadata = $this->summary['metadata'] ?? [];
          $metaCount = count($metadata);
          $highestColumn = $this->getHighestColumn();

          // ===== 1. Metadata =====
          if ($metaCount > 0) {
            $sheet->setCellValue('A1', 'INFORMASI EKSPOR');
            $sheet->mergeCells('A1:' . $highestColumn . '1');
            $sheet->getStyle('A1')->applyFromArray([
              'font' => ['bold' => true, 'size' => 13, 'color' => ['rgb' => '1F4E79']],
            ]);
            for ($i = 0; $i < $metaCount; $i++) {
              $row = $i + 2;
              $sheet->setCellValue('A'.$row, $metadata[$i]);
              $sheet->mergeCells('A'.$row.':'.$highestColumn.$row);
              $sheet->getStyle('A'.$row)->applyFromArray([
                'font' => ['size' => 10, 'italic' => true],
              ]);
            }
          }

          // ===== 2. Tabel Header =====
          $tableHeaderRow = $metaCount + 2; // 1 baris kosong setelah metadata
          $this->writeHeaders($sheet, $tableHeaderRow, $highestColumn);

          // ===== 3. Data =====
          $dataStartRow = $tableHeaderRow + $this->headerRowCount() + 1;
          $lastDataRow = $dataStartRow + count($this->data) - 1;
          $this->writeData($sheet, $dataStartRow, $highestColumn);
          $this->styleData($sheet, $dataStartRow, $lastDataRow, $highestColumn);

          // ===== 4. Subtotal =====
          $subStartRow = $lastDataRow + 2;
          $this->writeSubtotal($sheet, $subStartRow, $highestColumn);

          // ===== 5. Footer =====
          $footerRow = $subStartRow + $this->subtotalRowCount() + 1;
          $sheet->setCellValue('A'.$footerRow, 'Generated by VickyServer App - '.now()->format('d M Y H:i'));
          $sheet->mergeCells('A'.$footerRow.':'.$highestColumn.$footerRow);
          $sheet->getStyle('A'.$footerRow)->applyFromArray([
            'font' => ['italic' => true, 'color' => ['rgb' => '888888'], 'size' => 10],
            'alignment' => ['horizontal' => Alignment::HORIZONTAL_RIGHT],
          ]);
        },
      ];
    }

    // ----- Helper untuk kolom -----
    private function getHighestColumn(): string
    {
      return match ($this->type) {
        'transactions' => 'G',
        // A..G
        'transfers' => 'E',
        'budgets' => 'G',
      default => 'E',
      };
    }

    private function headerRowCount(): int
    {
      return $this->type === 'transactions' ? 2 : 1;
    }

    private function subtotalRowCount(): int
    {
      return match ($this->type) {
        'transactions' => 3,
        // pemasukan, pengeluaran, net
        'transfers' => 1,
        'budgets' => 2,
        // total limit, total spent, sisa
      default => 1,
      };
    }

    // ----- Tulis Header -----
    private function writeHeaders(Worksheet $sheet, int $startRow, string $highestColumn): void
    {
      $headerStyle = [
        'font' => ['bold' => true,
          'color' => ['rgb' => 'FFFFFF'],
          'size' => 12],
        'fill' => ['fillType' => Fill::FILL_SOLID,
          'startColor' => ['rgb' => '4F81BD']],
        'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER,
          'vertical' => Alignment::VERTICAL_CENTER],
        'borders' => ['allBorders' => ['borderStyle' => Border::BORDER_THIN]],
      ];

      if ($this->type === 'transactions') {
        // Baris 1 header
        $sheet->mergeCells('A'.$startRow.':A'.($startRow+1));
        $sheet->setCellValue('A'.$startRow, 'Tanggal');
        $sheet->mergeCells('B'.$startRow.':B'.($startRow+1));
        $sheet->setCellValue('B'.$startRow, 'Tipe');
        $sheet->mergeCells('C'.$startRow.':C'.($startRow+1));
        $sheet->setCellValue('C'.$startRow, 'Kategori');
        $sheet->mergeCells('D'.$startRow.':D'.($startRow+1));
        $sheet->setCellValue('D'.$startRow, 'Dompet');
        $sheet->mergeCells('E'.$startRow.':F'.$startRow);
        $sheet->setCellValue('E'.$startRow, 'Amount');
        $sheet->mergeCells('G'.$startRow.':G'.($startRow+1));
        $sheet->setCellValue('G'.$startRow, 'Deskripsi');
        $sheet->getStyle('A'.$startRow.':G'.($startRow+1))->applyFromArray($headerStyle);

        // Baris 2 header (sub‑header Amount)
        $startRow++;
        $sheet->setCellValue('E'.$startRow, 'Pemasukan');
        $sheet->setCellValue('F'.$startRow, 'Pengeluaran');
        $sheet->getStyle('E'.$startRow.':F'.$startRow)->applyFromArray($headerStyle);
      } else {
        // Header biasa 1 baris
        $headings = array_keys($this->data[0]);
        $col = 'A';
        foreach ($headings as $heading) {
          $sheet->setCellValue($col.$startRow, $heading);
          $col++;
        }
        $sheet->getStyle('A'.$startRow.':'.$highestColumn.$startRow)->applyFromArray($headerStyle);
      }
    }

    // ----- Tulis Data -----
    private function writeData(Worksheet $sheet, int $startRow, string $highestColumn): void
    {
      $row = $startRow;
      foreach ($this->data as $dataRow) {
        $col = 'A';
        foreach ($dataRow as $value) {
          // Ganti "-" menjadi 0
          $displayValue = ($value === '-' || $value === null) ? '0' : $value;
          $sheet->setCellValue($col.$row, $displayValue);
          $col++;
        }
        $row++;
      }
    }

    // ----- Style Data -----
    private function styleData(Worksheet $sheet, int $firstRow, int $lastRow, string $highestColumn): void
    {
      $dataStyle = [
        'borders' => ['allBorders' => ['borderStyle' => Border::BORDER_THIN]],
        'font' => ['size' => 10],
      ];

      // Semua data
      $sheet->getStyle('A'.$firstRow.':'.$highestColumn.$lastRow)->applyFromArray($dataStyle);

      // Rata kanan untuk kolom angka
      if ($this->type === 'transactions') {
        $sheet->getStyle('E'.$firstRow.':F'.$lastRow)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_RIGHT);
        // Warna hijau/merah
        for ($r = $firstRow; $r <= $lastRow; $r++) {
          $tipe = $sheet->getCell('B'.$r)->getValue();
          if ($tipe === 'Pemasukan') {
            $sheet->getStyle('E'.$r)->getFont()->getColor()->setRGB('28A745');
          } elseif ($tipe === 'Pengeluaran') {
            $sheet->getStyle('F'.$r)->getFont()->getColor()->setRGB('DC3545');
          }
        }
      } elseif ($this->type === 'transfers') {
        $sheet->getStyle('D'.$firstRow.':D'.$lastRow)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_RIGHT);
      } elseif ($this->type === 'budgets') {
        $sheet->getStyle('D'.$firstRow.':E'.$lastRow)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_RIGHT);
      }
    }

    // ----- Subtotal -----
    private function writeSubtotal(Worksheet $sheet, int $startRow, string $highestColumn): void
    {
      $format = $this->summary;
      $fmtNum = fn($v) => number_format($v, $format['precision'], $format['decimal_mark'], $format['thousands_separator']);
      $fmtCur = fn($v) => ($format['symbol_first'] ? $format['symbol'].' ' : '').$fmtNum($v).(!$format['symbol_first'] ? ' '.$format['symbol'] : '');

      $subStyle = [
        'font' => ['bold' => true,
          'size' => 11],
        'fill' => ['fillType' => Fill::FILL_SOLID,
          'startColor' => ['rgb' => 'D9E2F3']],
        'borders' => ['allBorders' => ['borderStyle' => Border::BORDER_THIN]],
        'alignment' => ['vertical' => Alignment::VERTICAL_CENTER],
      ];

      $sheet->setCellValue('A'.$startRow, 'SUBTOTAL');
      $sheet->mergeCells('A'.$startRow.':D'.$startRow);
      $sheet->getStyle('A'.$startRow)->applyFromArray($subStyle);

      if ($this->type === 'transactions') {
        $sheet->setCellValue('E'.$startRow, 'Pemasukan: '.$fmtCur($this->summary['total_income']));
        $sheet->getStyle('E'.$startRow)->applyFromArray($subStyle + ['alignment' => ['horizontal' => Alignment::HORIZONTAL_RIGHT]]);
        $startRow++;
        $sheet->setCellValue('E'.$startRow, 'Pengeluaran: '.$fmtCur($this->summary['total_expense']));
        $sheet->getStyle('E'.$startRow)->applyFromArray($subStyle + ['alignment' => ['horizontal' => Alignment::HORIZONTAL_RIGHT]]);
        $startRow++;
        $sheet->setCellValue('E'.$startRow, 'Net: '.$fmtCur($this->summary['net']));
        $sheet->getStyle('E'.$startRow)->applyFromArray($subStyle + ['alignment' => ['horizontal' => Alignment::HORIZONTAL_RIGHT]]);
      } elseif ($this->type === 'transfers') {
        $sheet->setCellValue('D'.$startRow, 'Total Transfer: '.$fmtCur($this->summary['total']));
        $sheet->getStyle('D'.$startRow)->applyFromArray($subStyle + ['alignment' => ['horizontal' => Alignment::HORIZONTAL_RIGHT]]);
      } elseif ($this->type === 'budgets') {
        $sheet->setCellValue('D'.$startRow, 'Total Limit: '.$fmtCur($this->summary['total_limit']));
        $sheet->setCellValue('E'.$startRow, 'Total Pengeluaran: '.$fmtCur($this->summary['total_spent']));
        $sheet->getStyle('D'.$startRow.':E'.$startRow)->applyFromArray($subStyle + ['alignment' => ['horizontal' => Alignment::HORIZONTAL_RIGHT]]);
        $startRow++;
        $sheet->setCellValue('D'.$startRow, 'Sisa: '.$fmtCur($this->summary['remaining']));
        $sheet->getStyle('D'.$startRow)->applyFromArray($subStyle + ['alignment' => ['horizontal' => Alignment::HORIZONTAL_RIGHT]]);
      }
    }
  }