<?php

namespace Modules\FinTech\Exports;

use Maatwebsite\Excel\Concerns\ {
  WithHeadings,
  WithStyles,
  ShouldAutoSize,
  WithEvents,
  WithTitle
};
use Maatwebsite\Excel\Events\AfterSheet;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;
use PhpOffice\PhpSpreadsheet\Style\ {
  Border,
  Fill,
  Font,
  Alignment
};

class DataExport implements WithHeadings, WithStyles, ShouldAutoSize, WithEvents, WithTitle
{
  protected string $type;
  protected array $data;
  protected array $summary;

  public function __construct(string $type, array $data, array $summary) {
    $this->type = $type;
    $this->data = $data;
    $this->summary = $summary;
  }

  public function headings(): array {
    return [[]];
  }
  public function title(): string
  {
    return match ($this->type) {
      'transactions' => 'Transaksi',
      'transfers' => 'Transfer',
      'budgets' => 'Budget',
      default => 'Data'
      };
    }
    public function styles(Worksheet $sheet) {}

    public function registerEvents(): array
    {
      return [
        AfterSheet::class => function (AfterSheet $event) {
          $sheet = $event->sheet->getDelegate();
          $metadata = $this->summary['metadata'] ?? [];
          $metaCount = count($metadata);
          $highestCol = $this->getHighestColumn();

          // === 1. Metadata ===
          if ($metaCount > 0) {
            $sheet->setCellValue('A1', 'INFORMASI EKSPOR');
            $sheet->mergeCells('A1:'.$highestCol.'1');
            $sheet->getStyle('A1')->applyFromArray([
              'font' => ['bold' => true, 'size' => 13, 'color' => ['rgb' => '1F4E79']],
            ]);
            for ($i = 0; $i < $metaCount; $i++) {
              $r = $i + 2;
              $sheet->setCellValue('A'.$r, $metadata[$i]);
              $sheet->mergeCells('A'.$r.':'.$highestCol.$r);
              $sheet->getStyle('A'.$r)->applyFromArray([
                'font' => ['size' => 10, 'italic' => true],
              ]);
            }
          }

          // === 2. Header Tabel ===
          $tableStart = $metaCount + 3; // 1 baris kosong setelah metadata
          $this->writeHeaders($sheet, $tableStart, $highestCol);
          $headerRows = $this->headerRowCount();
          $dataStart = $tableStart + $headerRows; // langsung di bawah header
          $lastData = $dataStart + count($this->data) - 1;

          // === 3. Data ===
          $this->writeData($sheet, $dataStart, $highestCol);
          $this->styleData($sheet, $dataStart, $lastData, $highestCol);

          // Auto-size columns
          foreach (range('A', $highestCol) as $col) {
            $sheet->getColumnDimension($col)->setAutoSize(true);
          }

          // === 4. Subtotal ===
          $subStart = $lastData + 2;
          $this->writeSubtotal($sheet, $subStart, $highestCol);

          // === 5. Footer ===
          $footerRow = $subStart + $this->subtotalDetailRows() + 1;
          $sheet->setCellValue('A'.$footerRow, 'Generated by VickyServer App - '.now()->format('d M Y H:i'));
          $sheet->mergeCells('A'.$footerRow.':'.$highestCol.$footerRow);
          $sheet->getStyle('A'.$footerRow)->applyFromArray([
            'font' => ['italic' => true, 'color' => ['rgb' => '888888'], 'size' => 10],
            'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER],
          ]);
        },
      ];
    }

    private function getHighestColumn(): string
    {
      return match ($this->type) {
        'transactions' => 'G',
        'transfers' => 'E',
        'budgets' => 'G',
      default => 'E',
      };
    }

    private function headerRowCount(): int
    {
      return $this->type === 'transactions' ? 2 : 1;
    }

    private function subtotalDetailRows(): int
    {
      return match ($this->type) {
        'transactions' => 3,
        'transfers' => 1,
        'budgets' => 2,
      default => 1,
      };
    }

    private function writeHeaders(Worksheet $sheet, int $startRow, string $highestCol): void
    {
      $style = [
        'font' => ['bold' => true,
          'color' => ['rgb' => 'FFFFFF'],
          'size' => 12],
        'fill' => ['fillType' => Fill::FILL_SOLID,
          'startColor' => ['rgb' => '4F81BD']],
        'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER,
          'vertical' => Alignment::VERTICAL_CENTER],
        'borders' => ['allBorders' => ['borderStyle' => Border::BORDER_THIN]],
      ];

      if ($this->type === 'transactions') {
        // Baris 1
        $sheet->mergeCells('A'.$startRow.':A'.($startRow+1));
        $sheet->setCellValue('A'.$startRow, 'Tanggal');
        $sheet->mergeCells('B'.$startRow.':B'.($startRow+1));
        $sheet->setCellValue('B'.$startRow, 'Tipe');
        $sheet->mergeCells('C'.$startRow.':C'.($startRow+1));
        $sheet->setCellValue('C'.$startRow, 'Kategori');
        $sheet->mergeCells('D'.$startRow.':D'.($startRow+1));
        $sheet->setCellValue('D'.$startRow, 'Dompet');
        $sheet->mergeCells('E'.$startRow.':F'.$startRow);
        $sheet->setCellValue('E'.$startRow, 'Amount');
        $sheet->mergeCells('G'.$startRow.':G'.($startRow+1));
        $sheet->setCellValue('G'.$startRow, 'Deskripsi');
        $sheet->getStyle('A'.$startRow.':G'.($startRow+1))->applyFromArray($style);
        // Baris 2
        $sheet->setCellValue('E'.($startRow+1), 'Pemasukan');
        $sheet->setCellValue('F'.($startRow+1), 'Pengeluaran');
      } else {
        $headings = array_keys($this->data[0]);
        $col = 'A';
        foreach ($headings as $h) {
          $sheet->setCellValue($col.$startRow, $h);
          $col++;
        }
        $sheet->getStyle('A'.$startRow.':'.$highestCol.$startRow)->applyFromArray($style);
      }
    }

    private function writeData(Worksheet $sheet, int $startRow, string $highestCol): void
    {
      $row = $startRow;
      foreach ($this->data as $line) {
        $col = 'A';
        foreach ($line as $val) {
          $display = ($val === '-' || $val === null) ? '0' : $val;
          $sheet->setCellValue($col.$row, $display);
          $col++;
        }
        $row++;
      }
    }

    private function styleData(Worksheet $sheet, int $first, int $last, string $highestCol): void
    {
      $sheet->getStyle('A'.$first.':'.$highestCol.$last)->applyFromArray([
        'borders' => ['allBorders' => ['borderStyle' => Border::BORDER_THIN]],
        'font' => ['size' => 10],
      ]);

      if ($this->type === 'transactions') {
        $sheet->getStyle('E'.$first.':F'.$last)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_RIGHT);
        for ($r = $first; $r <= $last; $r++) {
          $t = $sheet->getCell('B'.$r)->getValue();
          if ($t === 'Pemasukan') $sheet->getStyle('E'.$r)->getFont()->getColor()->setRGB('28A745');
          elseif ($t === 'Pengeluaran') $sheet->getStyle('F'.$r)->getFont()->getColor()->setRGB('DC3545');
        }
      } elseif ($this->type === 'transfers') {
        $sheet->getStyle('D'.$first.':D'.$last)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_RIGHT);
      } elseif ($this->type === 'budgets') {
        $sheet->getStyle('D'.$first.':E'.$last)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_RIGHT);
      }
    }

    private function writeSubtotal(Worksheet $sheet, int $startRow, string $highestCol): void
    {
      $f = $this->summary;
      $fmtNum = fn($v) => number_format($v, $f['precision'], $f['decimal_mark'], $f['thousands_separator']);
      $fmtCur = fn($v) => ($f['symbol_first'] ? $f['symbol'].' ' : '') . $fmtNum($v) . (!$f['symbol_first'] ? ' '.$f['symbol'] : '');

      $sty = [
        'font' => ['bold' => true,
          'size' => 11],
        'fill' => ['fillType' => Fill::FILL_SOLID,
          'startColor' => ['rgb' => 'D9E2F3']],
        'borders' => ['allBorders' => ['borderStyle' => Border::BORDER_THIN]],
      ];

      // Label SUBTOTAL
      $sheet->setCellValue('A'.$startRow, 'SUBTOTAL');
      $sheet->mergeCells('A'.$startRow.':'$this->getHighestColumn().$startRow);
      $sheet->getStyle('A'.$startRow)->applyFromArray($sty);

      $d = $startRow + 1;
      if ($this->type === 'transactions') {
        $sheet->setCellValue('A'.$d, 'Pemasukan: '.$fmtCur($f['total_income']));
        $sheet->mergeCells('A'.$d.':'.'B'.$d);
        $sheet->getStyle('A'.$d)->applyFromArray($sty + ['alignment' => ['horizontal' => Alignment::HORIZONTAL_LEFT]]);
        $d++;
        $sheet->setCellValue('A'.$d, 'Pengeluaran: '.$fmtCur($f['total_expense']));
        $sheet->mergeCells('A'.$d.':'.'B'.$d);
        $sheet->getStyle('A'.$d)->applyFromArray($sty + ['alignment' => ['horizontal' => Alignment::HORIZONTAL_RIGHT]]);
        $d++;
        $sheet->setCellValue('A'.$d, 'Net: '.$fmtCur($f['net']));
        $sheet->mergeCells('A'.$d.':'.'B'.$d);
        $sheet->getStyle('A'.$d)->applyFromArray($sty + ['alignment' => ['horizontal' => Alignment::HORIZONTAL_RIGHT]]);
      } elseif ($this->type === 'transfers') {
        $sheet->setCellValue('A'.$d, 'Total Transfer: '.$fmtCur($f['total']));
        $sheet->mergeCells('A'.$d.':'.'B'.$d);
        $sheet->getStyle('A'.$d)->applyFromArray($sty + ['alignment' => ['horizontal' => Alignment::HORIZONTAL_LEFT]]);
      } elseif ($this->type === 'budgets') {
        $sheet->setCellValue('D'.$d, 'Total Limit: '.$fmtCur($f['total_limit']));
        $sheet->setCellValue('E'.$d, 'Total Pengeluaran: '.$fmtCur($f['total_spent']));
        $sheet->getStyle('D'.$d.':E'.$d)->applyFromArray($sty + ['alignment' => ['horizontal' => Alignment::HORIZONTAL_RIGHT]]);
        $d++;
        $sheet->setCellValue('D'.$d, 'Sisa: '.$fmtCur($f['remaining']));
        $sheet->getStyle('D'.$d)->applyFromArray($sty + ['alignment' => ['horizontal' => Alignment::HORIZONTAL_RIGHT]]);
      }
    }
  }