<?php

namespace Modules\FinTech\Exports;

use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithStyles;
use Maatwebsite\Excel\Concerns\ShouldAutoSize;
use Maatwebsite\Excel\Concerns\WithEvents;
use Maatwebsite\Excel\Concerns\WithTitle;
use Maatwebsite\Excel\Events\AfterSheet;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\Font;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Worksheet\Drawing;
use mitoteam\jpgraph\MtJpGraph;

class ExcelDataExport implements WithHeadings, WithStyles, ShouldAutoSize, WithEvents, WithTitle
{
  protected string $type;
  protected array $data;
  protected array $summary;

  public function __construct(string $type, array $data, array $summary) {
    $this->type = $type;
    $this->data = $data;
    $this->summary = $summary;
  }

  public function headings(): array {
    // Jika data tersedia, gunakan key dari baris pertama
    if (!empty($this->data) && is_array($this->data[0])) {
      return array_keys($this->data[0]);
    }

    // Default headings per tipe
    return match ($this->type) {
      'transactions' => ['Tanggal',
        'Tipe',
        'Kategori',
        'Dompet',
        'Pemasukan',
        'Pengeluaran',
        'Deskripsi'],
      'transfers' => ['Tanggal',
        'Dari',
        'Ke',
        'Jumlah',
        'Deskripsi'],
      'budgets' => ['Kategori',
        'Dompet',
        'Periode',
        'Limit',
        'Pengeluaran',
        'Persentase',
        'Status'],
      default => [],
      };
    }

    public function title(): string
    {
      return match ($this->type) {
        'transactions' => 'Transaksi',
        'transfers' => 'Transfer',
        'budgets' => 'Budget',
      default => 'Data'
      };
    }
    public function styles(Worksheet $sheet) {}

    public function registerEvents(): array
    {
      return [
        AfterSheet::class => function (AfterSheet $event) {
          $sheet = $event->sheet->getDelegate();
          $metadata = $this->summary['metadata'] ?? [];
          $metaCount = count($metadata);
          $highestCol = $this->getHighestColumn();

          // 1. Metadata
          if ($metaCount > 0) {
            $sheet->setCellValue('A1', 'INFORMASI EKSPOR');
            $sheet->mergeCells('A1:'.$highestCol.'1');
            $sheet->getStyle('A1')->applyFromArray([
              'font' => ['bold' => true, 'size' => 13, 'color' => ['rgb' => '1F4E79']],
            ]);
            for ($i = 0; $i < $metaCount; $i++) {
              $r = $i + 2;
              $sheet->setCellValue('A'.$r, $metadata[$i]);
              $sheet->mergeCells('A'.$r.':'.$highestCol.$r);
              $sheet->getStyle('A'.$r)->applyFromArray([
                'font' => ['size' => 10, 'italic' => true],
              ]);
            }
          }

          // 2. Header Tabel
          $tableStart = $metaCount + 3;
          $this->writeHeaders($sheet, $tableStart, $highestCol);
          $headerRows = $this->headerRowCount();
          $dataStart = $tableStart + $headerRows;
          $lastData = $dataStart + count($this->data) - 1;

          // 3. Data
          $this->writeData($sheet, $dataStart, $highestCol);
          $this->styleData($sheet, $dataStart, $lastData, $highestCol);

          // Auto-size columns
          foreach (range('A', $highestCol) as $col) {
            $sheet->getColumnDimension($col)->setAutoSize(true);
          }

          // 4. Subtotal
          $subStart = $lastData + 2;
          $this->writeSubtotal($sheet, $subStart, $highestCol);
          $subDetailRows = $this->subtotalDetailRows();
          $subEnd = $subStart + $subDetailRows; // baris setelah detail subtotal

          // 5. Chart (sebelum footer)
          $chartRow = $subEnd + 2; // jarak 2 baris kosong setelah subtotal
          if ($this->type === 'transactions' && count($this->data) > 0) {
            $this->addChartToSheet($sheet, $chartRow, $this->data);
          }

          // 6. Footer (setelah chart)
          $footerRow = $chartRow + 40;
          $sheet->setCellValue('A'.$footerRow, 'Generated by '.config('app.name', 'Laravel').' App - '.now()->format('d M Y H:i'));
          $sheet->mergeCells('A'.$footerRow.':'.$highestCol.$footerRow);
          $sheet->getStyle('A'.$footerRow)->applyFromArray([
            'font' => ['italic' => true, 'color' => ['rgb' => '888888'], 'size' => 10],
            'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER],
          ]);
        },
      ];
    }

    private function getHighestColumn(): string
    {
      return match ($this->type) {
        'transactions' => 'G',
        'transfers' => 'E',
        'budgets' => 'G',
      default => 'E',
      };
    }

    private function headerRowCount(): int
    {
      return $this->type === 'transactions' ? 2 : 1;
    }

    private function subtotalDetailRows(): int
    {
      return match ($this->type) {
        'transactions' => 3,
        'transfers' => 1,
        'budgets' => 2,
      default => 1,
      };
    }

    private function writeHeaders(Worksheet $sheet, int $startRow, string $highestCol): void
    {
      $style = [
        'font' => ['bold' => true,
          'color' => ['rgb' => 'FFFFFF'],
          'size' => 12],
        'fill' => ['fillType' => Fill::FILL_SOLID,
          'startColor' => ['rgb' => '4F81BD']],
        'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER,
          'vertical' => Alignment::VERTICAL_CENTER],
        'borders' => ['allBorders' => ['borderStyle' => Border::BORDER_THIN]],
      ];
      $headings = $this->headings();

      if ($this->type === 'transactions') {
        // Baris 1
        $sheet->mergeCells('A'.$startRow.':A'.($startRow+1));
        $sheet->setCellValue('A'.$startRow, 'Tanggal');
        $sheet->mergeCells('B'.$startRow.':B'.($startRow+1));
        $sheet->setCellValue('B'.$startRow, 'Tipe');
        $sheet->mergeCells('C'.$startRow.':C'.($startRow+1));
        $sheet->setCellValue('C'.$startRow, 'Kategori');
        $sheet->mergeCells('D'.$startRow.':D'.($startRow+1));
        $sheet->setCellValue('D'.$startRow, 'Dompet');
        $sheet->mergeCells('E'.$startRow.':F'.$startRow);
        $sheet->setCellValue('E'.$startRow, 'Amount');
        $sheet->mergeCells('G'.$startRow.':G'.($startRow+1));
        $sheet->setCellValue('G'.$startRow, 'Deskripsi');
        $sheet->getStyle('A'.$startRow.':G'.($startRow+1))->applyFromArray($style);
        // Baris 2
        $sheet->setCellValue('E'.($startRow+1), 'Pemasukan');
        $sheet->setCellValue('F'.($startRow+1), 'Pengeluaran');
      } else {
        $col = 'A';
        foreach ($headings as $h) {
          $sheet->setCellValue($col.$startRow, $h);
          $col++;
        }
        $sheet->getStyle('A'.$startRow.':'.$highestCol.$startRow)->applyFromArray($style);
      }
    }

    private function writeData(Worksheet $sheet, int $startRow, string $highestCol): void
    {
      if (empty($this->data)) {
        // Tulis "Tidak ada data" di baris pertama, merge semua kolom
        $sheet->setCellValue('A' . $startRow, 'Tidak ada data');
        $sheet->mergeCells('A' . $startRow . ':' . $highestCol . $startRow);
        $sheet->getStyle('A' . $startRow)->applyFromArray([
          'font' => ['italic' => true, 'color' => ['rgb' => '888888']],
          'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER],
          'borders' => ['allBorders' => ['borderStyle' => Border::BORDER_THIN]],
        ]);
        return;
      }

      $row = $startRow;
      foreach ($this->data as $line) {
        $col = 'A';
        foreach ($line as $val) {
          $display = ($val === '-' || $val === null) ? '0' : $val;
          $sheet->setCellValue($col.$row, $display);
          $col++;
        }
        $row++;
      }
    }

    private function styleData(Worksheet $sheet, int $first, int $last, string $highestCol): void
    {
      $sheet->getStyle('A'.$first.':'.$highestCol.$last)->applyFromArray([
        'borders' => ['allBorders' => ['borderStyle' => Border::BORDER_THIN]],
        'font' => ['size' => 10],
      ]);

      if ($this->type === 'transactions') {
        $sheet->getStyle('E'.$first.':F'.$last)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_RIGHT);
        for ($r = $first; $r <= $last; $r++) {
          $t = $sheet->getCell('B'.$r)->getValue();
          if ($t === 'Pemasukan') $sheet->getStyle('E'.$r)->getFont()->getColor()->setRGB('28A745');
          elseif ($t === 'Pengeluaran') $sheet->getStyle('F'.$r)->getFont()->getColor()->setRGB('DC3545');
        }
      } elseif ($this->type === 'transfers') {
        $sheet->getStyle('D'.$first.':D'.$last)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_RIGHT);
      } elseif ($this->type === 'budgets') {
        $sheet->getStyle('D'.$first.':E'.$last)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_RIGHT);
      }
    }

    private function writeSubtotal(Worksheet $sheet, int $startRow, string $highestCol): void
    {
      $f = $this->summary;
      $fmtNum = fn($v) => number_format($v, $f['precision'], $f['decimal_mark'], $f['thousands_separator']);
      $fmtCur = fn($v) => ($f['symbol_first'] ? $f['symbol'].' ' : '') . $fmtNum($v) . (!$f['symbol_first'] ? ' '.$f['symbol'] : '');

      $sty = [
        'font' => ['bold' => true,
          'size' => 11],
        'fill' => ['fillType' => Fill::FILL_SOLID,
          'startColor' => ['rgb' => 'D9E2F3']],
        'borders' => ['allBorders' => ['borderStyle' => Border::BORDER_THIN]],
      ];

      // Label SUBTOTAL
      $sheet->setCellValue('A'.$startRow, 'SUBTOTAL');
      $sheet->mergeCells('A'.$startRow.':'.$highestCol.$startRow);
      $sheet->getStyle('A'.$startRow.':'.$highestCol.$startRow)->applyFromArray($sty);

      $d = $startRow + 1;
      if ($this->type === 'transactions') {
        $sheet->setCellValue('A'.$d, 'Pemasukan: '.$fmtCur($f['total_income']));
        $sheet->mergeCells('A'.$d.':'.$highestCol.$d);
        $sheet->getStyle('A'.$d.':'.$highestCol.$d)->applyFromArray($sty + ['alignment' => ['horizontal' => Alignment::HORIZONTAL_LEFT]]);
        $d++;
        $sheet->setCellValue('A'.$d, 'Pengeluaran: '.$fmtCur($f['total_expense']));
        $sheet->mergeCells('A'.$d.':'.$highestCol.$d);
        $sheet->getStyle('A'.$d.':'.$highestCol.$d)->applyFromArray($sty+ ['alignment' => ['horizontal' => Alignment::HORIZONTAL_LEFT]]);
        $d++;
        $sheet->setCellValue('A'.$d, 'Net: '.$fmtCur($f['net']));
        $sheet->mergeCells('A'.$d.':'.$highestCol.$d);
        $sheet->getStyle('A'.$d.':'.$highestCol.$d)->applyFromArray($sty+ ['alignment' => ['horizontal' => Alignment::HORIZONTAL_LEFT]]);
      } elseif ($this->type === 'transfers') {
        $sheet->setCellValue('A'.$d, 'Total Transfer: '.$fmtCur($f['total']));
        $sheet->mergeCells('A'.$d.':'.$highestCol.$d);
        $sheet->getStyle('A'.$d.':'.$highestCol.$d)->applyFromArray($sty + ['alignment' => ['horizontal' => Alignment::HORIZONTAL_LEFT]]);
      } elseif ($this->type === 'budgets') {
        // Baris 1: Total Limit & Total Pengeluaran
        $sheet->setCellValue('A'.$d, '');
        $sheet->setCellValue('B'.$d, '');
        $sheet->setCellValue('C'.$d, '');
        $sheet->setCellValue('D'.$d, 'Total Limit: '.$fmtCur($f['total_limit']));
        $sheet->setCellValue('E'.$d, 'Total Pengeluaran: '.$fmtCur($f['total_spent']));
        $sheet->setCellValue('F'.$d, '');
        $sheet->setCellValue('G'.$d, '');
        $sheet->getStyle('A'.$d.':'.$highestCol.$d)->applyFromArray($sty);
        // Rata kanan untuk sel angka
        $sheet->getStyle('D'.$d)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_RIGHT);
        $sheet->getStyle('E'.$d)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_RIGHT);

        $d++;

        // Baris 2: Sisa
        $sheet->setCellValue('A'.$d, '');
        $sheet->setCellValue('B'.$d, '');
        $sheet->setCellValue('C'.$d, '');
        $sheet->setCellValue('D'.$d, 'Sisa: '.$fmtCur($f['remaining']));
        $sheet->setCellValue('E'.$d, '');
        $sheet->setCellValue('F'.$d, '');
        $sheet->setCellValue('G'.$d, '');
        $sheet->getStyle('A'.$d.':'.$highestCol.$d)->applyFromArray($sty);
        $sheet->getStyle('D'.$d)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_RIGHT);
      }
    }

    protected function addChartToSheet(Worksheet $sheet, int $startRow, array $data): void
    {
      MtJpGraph::load(['bar']);

      // Siapkan data
      $labels = [];
      $incomes = [];
      $expenses = [];
      foreach ($data as $row) {
        // Format tanggal sudah berupa "d/m/Y", ambil langsung
        $labels[] = $row['Tanggal'] ?? '';
        // Bersihkan format uang
        $incomes[] = (float) str_replace(['Rp', '.', ','], '', $row['Pemasukan'] ?? '0');
        $expenses[] = (float) str_replace(['Rp', '.', ','], '', $row['Pengeluaran'] ?? '0');
      }
      $dataCount = count($data);

      // Lebar chart dinamis, minimal 800, maksimal 2000
      $chartWidth = min(2000, max(800, $dataCount * 18));

      // Buat objek Graph
      $graph = new \Graph($chartWidth, 400);
      $graph->SetScale('textlin');
      $graph->title->Set('Pemasukan vs Pengeluaran');
      $graph->xaxis->title->Set('Tanggal');
      $graph->yaxis->title->Set('Jumlah');

      // --- Pengaturan sumbu X ---
      $maxLabels = 30; // maksimal label yang ditampilkan
      if ($dataCount > $maxLabels) {
        $step = ceil($dataCount / $maxLabels);
        // Ambil hanya label pada indeks tertentu
        $visibleLabels = [];
        for ($i = 0; $i < $dataCount; $i += $step) {
          // Tetap gunakan format tanggal lengkap
          $visibleLabels[] = $labels[$i];
        }
        // Atur tick dan label
        $graph->xaxis->SetTickLabels($visibleLabels);
        $graph->xaxis->SetTextTickInterval($step, 0);
      } else {
        $graph->xaxis->SetTickLabels($labels);
      }
      // Miringkan label agar muat
      $graph->xaxis->SetLabelAngle(45);
      // Perkecil font sumbu X
      $graph->xaxis->SetFont(FF_DEFAULT, FS_NORMAL, 7);

      // --- Pengaturan sumbu Y (format angka pendek) ---
      $graph->yaxis->SetFont(FF_DEFAULT, FS_NORMAL, 8);
      // Callback untuk format ribuan
      $graph->yaxis->scale->SetLabelFormatCallback(function($val) {
        return number_format($val, 0, ',', '.');
      });
      $graph->yaxis->scale->SetAutoMin(0);

      // --- Plot batang ---
      $incomePlot = new \BarPlot($incomes);
      $expensePlot = new \BarPlot($expenses);
      $incomePlot->SetFillColor('#28A745');
      $expensePlot->SetFillColor('#DC3545');
      // HILANGKAN legenda
      $incomePlot->SetLegend(null);
      $expensePlot->SetLegend(null);

      $groupPlot = new \GroupBarPlot([$incomePlot, $expensePlot]);
      $graph->Add($groupPlot);

      // Simpan gambar sementara
      $tempFile = tempnam(sys_get_temp_dir(), 'chart_').'.png';
      $graph->Stroke($tempFile);

      // Sisipkan ke worksheet
      $drawing = new Drawing();
      $drawing->setPath($tempFile);
      $drawing->setCoordinates('B' . $startRow);
      $drawing->setWidth($chartWidth);
      $drawing->setHeight(400);
      $drawing->setWorksheet($sheet);

      register_shutdown_function(function () use ($tempFile) {
        if (file_exists($tempFile)) unlink($tempFile);
      });
    }
  }