<?php

namespace Modules\FinTech\Exports;

use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithStyles;
use Maatwebsite\Excel\Concerns\ShouldAutoSize;
use Maatwebsite\Excel\Concerns\WithEvents;
use Maatwebsite\Excel\Concerns\WithTitle;
use Maatwebsite\Excel\Events\AfterSheet;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\Font;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Worksheet\Drawing;
use mitoteam\jpgraph\MtJpGraph;

class ExcelDataExport implements WithHeadings, WithStyles, ShouldAutoSize, WithEvents, WithTitle
{
  protected string $type;
  protected array $data;
  protected array $summary;

  public function __construct(string $type, array $data, array $summary) {
    $this->type = $type;
    $this->data = $data;
    $this->summary = $summary;
  }

  public function headings(): array {
    // Jika data tersedia, gunakan key dari baris pertama
    if (!empty($this->data) && is_array($this->data[0])) {
      return array_keys($this->data[0]);
    }

    // Default headings per tipe
    return match ($this->type) {
      'transactions' => ['Tanggal',
        'Tipe',
        'Kategori',
        'Dompet',
        'Pemasukan',
        'Pengeluaran',
        'Deskripsi'],
      'transfers' => ['Tanggal',
        'Dari',
        'Ke',
        'Jumlah',
        'Deskripsi'],
      'budgets' => ['Kategori',
        'Dompet',
        'Periode',
        'Limit',
        'Pengeluaran',
        'Persentase',
        'Status'],
      default => [],
      };
    }

    public function title(): string
    {
      return match ($this->type) {
        'transactions' => 'Transaksi',
        'transfers' => 'Transfer',
        'budgets' => 'Budget',
      default => 'Data'
      };
    }
    public function styles(Worksheet $sheet) {}

    public function registerEvents(): array
    {
      return [
        AfterSheet::class => function (AfterSheet $event) {
          $sheet = $event->sheet->getDelegate();
          $metadata = $this->summary['metadata'] ?? [];
          $metaCount = count($metadata);
          $highestCol = $this->getHighestColumn();

          // 1. Metadata
          if ($metaCount > 0) {
            $sheet->setCellValue('A1', 'INFORMASI EKSPOR');
            $sheet->mergeCells('A1:'.$highestCol.'1');
            $sheet->getStyle('A1')->applyFromArray([
              'font' => ['bold' => true, 'size' => 13, 'color' => ['rgb' => '1F4E79']],
            ]);
            for ($i = 0; $i < $metaCount; $i++) {
              $r = $i + 2;
              $sheet->setCellValue('A'.$r, $metadata[$i]);
              $sheet->mergeCells('A'.$r.':'.$highestCol.$r);
              $sheet->getStyle('A'.$r)->applyFromArray([
                'font' => ['size' => 10, 'italic' => true],
              ]);
            }
          }

          // 2. Header Tabel
          $tableStart = $metaCount + 3;
          $this->writeHeaders($sheet, $tableStart, $highestCol);
          $headerRows = $this->headerRowCount();
          $dataStart = $tableStart + $headerRows;
          $lastData = $dataStart + count($this->data) - 1;

          // 3. Data
          $this->writeData($sheet, $dataStart, $highestCol);
          $this->styleData($sheet, $dataStart, $lastData, $highestCol);
          // 3b. Sisipkan ringkasan bulanan
          $this->insertMonthlySummaries($sheet, $dataStart, $lastData, $highestCol);

          // Auto-size columns
          foreach (range('A', $highestCol) as $col) {
            $sheet->getColumnDimension($col)->setAutoSize(true);
          }

          // 4. Subtotal
          $subStart = $lastData + 2;
          $this->writeSubtotal($sheet, $subStart, $highestCol);
          $subDetailRows = $this->subtotalDetailRows();
          $subEnd = $subStart + $subDetailRows; // baris setelah detail subtotal

          // 5. Chart (sebelum footer)
          $chartRow = $subEnd + 2; // jarak 2 baris kosong setelah subtotal
          if ($this->type === 'transactions' && count($this->data) > 0) {
            $this->addChartToSheet($sheet, $chartRow, $this->data);
          }

          // 6. Footer (setelah chart)
          $footerRow = $chartRow + 40;
          $sheet->setCellValue('A'.$footerRow, 'Generated by '.config('app.name', 'Laravel').' App - '.now()->format('d M Y H:i'));
          $sheet->mergeCells('A'.$footerRow.':'.$highestCol.$footerRow);
          $sheet->getStyle('A'.$footerRow)->applyFromArray([
            'font' => ['italic' => true, 'color' => ['rgb' => '888888'], 'size' => 10],
            'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER],
          ]);
        },
      ];
    }

    private function getHighestColumn(): string
    {
      return match ($this->type) {
        'transactions' => 'G',
        'transfers' => 'E',
        'budgets' => 'G',
      default => 'E',
      };
    }

    private function headerRowCount(): int
    {
      return $this->type === 'transactions' ? 2 : 1;
    }

    private function subtotalDetailRows(): int
    {
      return match ($this->type) {
        'transactions' => 3,
        'transfers' => 1,
        'budgets' => 2,
      default => 1,
      };
    }

    private function writeHeaders(Worksheet $sheet, int $startRow, string $highestCol): void
    {
      $style = [
        'font' => ['bold' => true,
          'color' => ['rgb' => 'FFFFFF'],
          'size' => 12],
        'fill' => ['fillType' => Fill::FILL_SOLID,
          'startColor' => ['rgb' => '4F81BD']],
        'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER,
          'vertical' => Alignment::VERTICAL_CENTER],
        'borders' => ['allBorders' => ['borderStyle' => Border::BORDER_THIN]],
      ];
      $headings = $this->headings();

      if ($this->type === 'transactions') {
        // Baris 1
        $sheet->mergeCells('A'.$startRow.':A'.($startRow+1));
        $sheet->setCellValue('A'.$startRow, 'Tanggal');
        $sheet->mergeCells('B'.$startRow.':B'.($startRow+1));
        $sheet->setCellValue('B'.$startRow, 'Tipe');
        $sheet->mergeCells('C'.$startRow.':C'.($startRow+1));
        $sheet->setCellValue('C'.$startRow, 'Kategori');
        $sheet->mergeCells('D'.$startRow.':D'.($startRow+1));
        $sheet->setCellValue('D'.$startRow, 'Dompet');
        $sheet->mergeCells('E'.$startRow.':F'.$startRow);
        $sheet->setCellValue('E'.$startRow, 'Amount');
        $sheet->mergeCells('G'.$startRow.':G'.($startRow+1));
        $sheet->setCellValue('G'.$startRow, 'Deskripsi');
        $sheet->getStyle('A'.$startRow.':G'.($startRow+1))->applyFromArray($style);
        // Baris 2
        $sheet->setCellValue('E'.($startRow+1), 'Pemasukan');
        $sheet->setCellValue('F'.($startRow+1), 'Pengeluaran');
      } else {
        $col = 'A';
        foreach ($headings as $h) {
          $sheet->setCellValue($col.$startRow, $h);
          $col++;
        }
        $sheet->getStyle('A'.$startRow.':'.$highestCol.$startRow)->applyFromArray($style);
      }
    }

    private function writeData(Worksheet $sheet, int $startRow, string $highestCol): void
    {
      if (empty($this->data)) {
        // Tulis "Tidak ada data" di baris pertama, merge semua kolom
        $sheet->setCellValue('A' . $startRow, 'Tidak ada data');
        $sheet->mergeCells('A' . $startRow . ':' . $highestCol . $startRow);
        $sheet->getStyle('A' . $startRow)->applyFromArray([
          'font' => ['italic' => true, 'color' => ['rgb' => '888888']],
          'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER],
          'borders' => ['allBorders' => ['borderStyle' => Border::BORDER_THIN]],
        ]);
        return;
      }

      $row = $startRow;
      foreach ($this->data as $line) {
        $col = 'A';
        foreach ($line as $val) {
          $display = ($val === '-' || $val === null) ? '0' : $val;
          $sheet->setCellValue($col.$row, $display);
          $col++;
        }
        $row++;
      }
    }

    private function styleData(Worksheet $sheet, int $first, int $last, string $highestCol): void
    {
      $sheet->getStyle('A'.$first.':'.$highestCol.$last)->applyFromArray([
        'borders' => ['allBorders' => ['borderStyle' => Border::BORDER_THIN]],
        'font' => ['size' => 10],
      ]);

      if ($this->type === 'transactions') {
        $sheet->getStyle('E'.$first.':F'.$last)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_RIGHT);
        for ($r = $first; $r <= $last; $r++) {
          $t = $sheet->getCell('B'.$r)->getValue();
          if ($t === 'Pemasukan') $sheet->getStyle('E'.$r)->getFont()->getColor()->setRGB('28A745');
          elseif ($t === 'Pengeluaran') $sheet->getStyle('F'.$r)->getFont()->getColor()->setRGB('DC3545');
        }
      } elseif ($this->type === 'transfers') {
        $sheet->getStyle('D'.$first.':D'.$last)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_RIGHT);
      } elseif ($this->type === 'budgets') {
        $sheet->getStyle('D'.$first.':E'.$last)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_RIGHT);
      }
    }

    // Di dalam class, tambahkan method baru:
    private function insertMonthlySummaries(Worksheet $sheet, int $dataStartRow, int &$lastDataRow, string $highestCol): void
    {
      $insertions = [];
      $currentMonth = null;
      $totalIncome = 0;
      $totalExpense = 0;
      $startIdx = 0;
      $dataCount = count($this->data);

      for ($i = 0; $i < $dataCount; $i++) {
        $rowData = $this->data[$i];
        $date = \DateTime::createFromFormat('d/m/Y', $rowData['Tanggal'] ?? '');
        $month = $date ? $date->format('Y-m') : null;

        if ($currentMonth === null) {
          $currentMonth = $month;
          $totalIncome = 0;
          $totalExpense = 0;
          $startIdx = $i;
        }

        if ($month !== $currentMonth) {
          // Bulan sebelumnya berakhir di $i-1
          $endIdx = $i - 1;
          $insertRow = $dataStartRow + $endIdx + 1; // setelah baris terakhir bulan itu
          $insertions[] = [
            'row' => $insertRow,
            'income' => $totalIncome,
            'expense' => $totalExpense,
            'monthKey' => $currentMonth,
          ];
          // Reset untuk bulan baru
          $currentMonth = $month;
          $totalIncome = 0;
          $totalExpense = 0;
          $startIdx = $i;
        }

        // Akumulasi
        $incomeVal = (float) str_replace(['Rp', '.', ','], '', $rowData['Pemasukan'] ?? '0');
        $expenseVal = (float) str_replace(['Rp', '.', ','], '', $rowData['Pengeluaran'] ?? '0');
        $totalIncome += $incomeVal;
        $totalExpense += $expenseVal;
      }

      // Bulan terakhir
      if ($currentMonth !== null) {
        $endIdx = $dataCount - 1;
        $insertRow = $dataStartRow + $endIdx + 1;
        $insertions[] = [
          'row' => $insertRow,
          'income' => $totalIncome,
          'expense' => $totalExpense,
          'monthKey' => $currentMonth,
        ];
      }

      // Urutkan dari baris terbesar agar penyisipan tidak mengacaukan indeks
      usort($insertions, function($a, $b) {
        return $b['row'] - $a['row'];
      });

      $fmt = $this->summary;
      $fmtNum = fn($v) => number_format($v, $fmt['precision'], $fmt['decimal_mark'], $fmt['thousands_separator']);
      $fmtCur = fn($v) => ($fmt['symbol_first'] ? $fmt['symbol'].' ' : '') . $fmtNum($v) . (!$fmt['symbol_first'] ? ' '.$fmt['symbol'] : '');

      foreach ($insertions as $ins) {
        $r = $ins['row'];
        $sheet->insertNewRowBefore($r, 1); // sisipkan 1 baris kosong di posisi $r
        // Tulis data ringkasan
        $sheet->setCellValue('A'.$r, 'Jumlah '.$ins['monthKey']);
        $sheet->mergeCells('A'.$r.':D'.$r);
        $sheet->setCellValue('E'.$r, $fmtCur($ins['income'] ?? 0));
        $sheet->setCellValue('F'.$r, $fmtCur($ins['expense'] ?? 0));
        $diff = ($ins['income'] ?? 0) - ($ins['expense'] ?? 0);
        $sheet->setCellValue('G'.$r, $fmtCur($diff));
        // Styling ringkasan
        $sty = [
          'font' => ['bold' => true,
            'size' => 10],
          'fill' => ['fillType' => Fill::FILL_SOLID,
            'startColor' => ['rgb' => 'E6F0FF']],
          'borders' => ['allBorders' => ['borderStyle' => Border::BORDER_THIN]],
          'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER,
            'vertical' => Alignment::VERTICAL_CENTER],
        ];
        $sheet->getStyle('A'.$r.':'.$highestCol.$r)->applyFromArray($sty);
        // Warna pemasukan/pengeluaran tetap
        $sheet->getStyle('E'.$r)->getFont()->getColor()->setRGB('28A745');
        $sheet->getStyle('F'.$r)->getFont()->getColor()->setRGB('DC3545');
        if ($diff >= 0) {
          $sheet->getStyle('G'.$r)->getFont()->getColor()->setRGB('28A745');
        } else {
          $sheet->getStyle('G'.$r)->getFont()->getColor()->setRGB('DC3545');
        }

        $lastDataRow++; // setiap sisipan menambah jumlah baris
      }
    }

    private function writeSubtotal(Worksheet $sheet, int $startRow, string $highestCol): void
    {
      $f = $this->summary;
      $fmtNum = fn($v) => number_format($v, $f['precision'], $f['decimal_mark'], $f['thousands_separator']);
      $fmtCur = fn($v) => ($f['symbol_first'] ? $f['symbol'].' ' : '') . $fmtNum($v) . (!$f['symbol_first'] ? ' '.$f['symbol'] : '');

      $sty = [
        'font' => ['bold' => true,
          'size' => 11],
        'fill' => ['fillType' => Fill::FILL_SOLID,
          'startColor' => ['rgb' => 'D9E2F3']],
        'borders' => ['allBorders' => ['borderStyle' => Border::BORDER_THIN]],
      ];

      // Label SUBTOTAL
      $sheet->setCellValue('A'.$startRow, 'SUBTOTAL');
      $sheet->mergeCells('A'.$startRow.':'.$highestCol.$startRow);
      $sheet->getStyle('A'.$startRow.':'.$highestCol.$startRow)->applyFromArray($sty);

      $d = $startRow + 1;
      if ($this->type === 'transactions') {
        $sheet->setCellValue('A'.$d, 'Pemasukan: '.$fmtCur($f['total_income']));
        $sheet->mergeCells('A'.$d.':'.$highestCol.$d);
        $sheet->getStyle('A'.$d.':'.$highestCol.$d)->applyFromArray($sty + ['alignment' => ['horizontal' => Alignment::HORIZONTAL_LEFT]]);
        $d++;
        $sheet->setCellValue('A'.$d, 'Pengeluaran: '.$fmtCur($f['total_expense']));
        $sheet->mergeCells('A'.$d.':'.$highestCol.$d);
        $sheet->getStyle('A'.$d.':'.$highestCol.$d)->applyFromArray($sty+ ['alignment' => ['horizontal' => Alignment::HORIZONTAL_LEFT]]);
        $d++;
        $sheet->setCellValue('A'.$d, 'Net: '.$fmtCur($f['net']));
        $sheet->mergeCells('A'.$d.':'.$highestCol.$d);
        $sheet->getStyle('A'.$d.':'.$highestCol.$d)->applyFromArray($sty+ ['alignment' => ['horizontal' => Alignment::HORIZONTAL_LEFT]]);
      } elseif ($this->type === 'transfers') {
        $sheet->setCellValue('A'.$d, 'Total Transfer: '.$fmtCur($f['total']));
        $sheet->mergeCells('A'.$d.':'.$highestCol.$d);
        $sheet->getStyle('A'.$d.':'.$highestCol.$d)->applyFromArray($sty + ['alignment' => ['horizontal' => Alignment::HORIZONTAL_LEFT]]);
      } elseif ($this->type === 'budgets') {
        // Baris 1: Total Limit & Total Pengeluaran
        $sheet->setCellValue('A'.$d, '');
        $sheet->setCellValue('B'.$d, '');
        $sheet->setCellValue('C'.$d, '');
        $sheet->setCellValue('D'.$d, 'Total Limit: '.$fmtCur($f['total_limit']));
        $sheet->setCellValue('E'.$d, 'Total Pengeluaran: '.$fmtCur($f['total_spent']));
        $sheet->setCellValue('F'.$d, '');
        $sheet->setCellValue('G'.$d, '');
        $sheet->getStyle('A'.$d.':'.$highestCol.$d)->applyFromArray($sty);
        // Rata kanan untuk sel angka
        $sheet->getStyle('D'.$d)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_RIGHT);
        $sheet->getStyle('E'.$d)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_RIGHT);

        $d++;

        // Baris 2: Sisa
        $sheet->setCellValue('A'.$d, '');
        $sheet->setCellValue('B'.$d, '');
        $sheet->setCellValue('C'.$d, '');
        $sheet->setCellValue('D'.$d, 'Sisa: '.$fmtCur($f['remaining']));
        $sheet->setCellValue('E'.$d, '');
        $sheet->setCellValue('F'.$d, '');
        $sheet->setCellValue('G'.$d, '');
        $sheet->getStyle('A'.$d.':'.$highestCol.$d)->applyFromArray($sty);
        $sheet->getStyle('D'.$d)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_RIGHT);
      }
    }

    protected function addChartToSheet(Worksheet $sheet, int $startRow, array $data): void
    {
      MtJpGraph::load(['bar']);

      // 1. Urutkan data dari tanggal terlama ke terbaru
      usort($data, function ($a, $b) {
        $dateA = \DateTime::createFromFormat('d/m/Y', $a['Tanggal'] ?? '') ?: new \DateTime('1970-01-01');
        $dateB = \DateTime::createFromFormat('d/m/Y', $b['Tanggal'] ?? '') ?: new \DateTime('1970-01-01');
        return $dateA <=> $dateB;
      });

      $firstDate = \DateTime::createFromFormat('d/m/Y', $data[0]['Tanggal'] ?? '');
      $lastDate = \DateTime::createFromFormat('d/m/Y', $data[count($data)-1]['Tanggal'] ?? '');
      if (!$firstDate || !$lastDate) {
        // Fallback: tidak ada tanggal valid, hentikan
        return;
      }

      $interval = $firstDate->diff($lastDate);
      $totalYears = $interval->y + ($interval->m > 0 ? 1 : 0); // aproksimasi tahun

      $labels = [];
      $incomes = [];
      $expenses = [];

      if ($totalYears >= 3) {
        // ----- Rangkum per TAHUN -----
        $grouped = [];
        foreach ($data as $row) {
          $date = \DateTime::createFromFormat('d/m/Y', $row['Tanggal'] ?? '');
          if (!$date) continue;
          $yearKey = $date->format('Y');
          if (!isset($grouped[$yearKey])) {
            $grouped[$yearKey] = ['income' => 0,
              'expense' => 0];
          }
          $grouped[$yearKey]['income'] += (float) str_replace(['Rp', '.', ','], '', $row['Pemasukan'] ?? '0');
          $grouped[$yearKey]['expense'] += (float) str_replace(['Rp', '.', ','], '', $row['Pengeluaran'] ?? '0');
        }
        ksort($grouped);
        foreach ($grouped as $yearKey => $values) {
          $labels[] = $yearKey;
          $incomes[] = $values['income'];
          $expenses[] = $values['expense'];
        }
        $xAxisTitle = 'Tahun';
        $chartWidth = min(2000, max(800, count($labels) * 80));
      } elseif ($interval->m > 0 || $interval->y > 0) {
        // ----- Rangkum per BULAN (lebih dari 1 bulan) -----
        $grouped = [];
        foreach ($data as $row) {
          $date = \DateTime::createFromFormat('d/m/Y', $row['Tanggal'] ?? '');
          if (!$date) continue;
          $monthKey = $date->format('Y-m');
          if (!isset($grouped[$monthKey])) {
            $grouped[$monthKey] = ['income' => 0,
              'expense' => 0];
          }
          $grouped[$monthKey]['income'] += (float) str_replace(['Rp', '.', ','], '', $row['Pemasukan'] ?? '0');
          $grouped[$monthKey]['expense'] += (float) str_replace(['Rp', '.', ','], '', $row['Pengeluaran'] ?? '0');
        }
        ksort($grouped);
        foreach ($grouped as $monthKey => $values) {
          $date = \DateTime::createFromFormat('!Y-m', $monthKey);
          $labels[] = $date ? $date->format('M Y') : $monthKey;
          $incomes[] = $values['income'];
          $expenses[] = $values['expense'];
        }
        $xAxisTitle = 'Bulan';
        $chartWidth = min(2000, max(800, count($labels) * 50));
      } else {
        // ----- Tampilkan per TANGGAL -----
        foreach ($data as $row) {
          $date = \DateTime::createFromFormat('d/m/Y', $row['Tanggal'] ?? '');
          $labels[] = $date ? $date->format('j M Y') : ($row['Tanggal'] ?? '');
          $incomes[] = (float) str_replace(['Rp', '.', ','], '', $row['Pemasukan'] ?? '0');
          $expenses[] = (float) str_replace(['Rp', '.', ','], '', $row['Pengeluaran'] ?? '0');
        }
        $xAxisTitle = 'Tanggal';
        $chartWidth = min(2000, max(800, count($labels) * 18));
      }

      // Buat chart
      $graph = new \Graph($chartWidth, 400);
      $graph->SetScale('textlin');
      $graph->title->Set('Pemasukan vs Pengeluaran');
      $graph->xaxis->title->Set($xAxisTitle);
      $graph->yaxis->title->Set('Jumlah');

      // Sumbu X
      $graph->xaxis->SetTickLabels($labels);
      $graph->xaxis->SetLabelAngle(45);
      $graph->xaxis->SetFont(FF_DEFAULT, FS_NORMAL, 8);

      // Sumbu Y
      $graph->yaxis->SetFont(FF_DEFAULT, FS_NORMAL, 8);
      $graph->yaxis->scale->SetAutoMin(0);

      // Plot
      $incomePlot = new \BarPlot($incomes);
      $expensePlot = new \BarPlot($expenses);
      $incomePlot->SetFillColor('#28A745');
      $expensePlot->SetFillColor('#DC3545');
      $incomePlot->SetLegend(null);
      $expensePlot->SetLegend(null);

      $groupPlot = new \GroupBarPlot([$incomePlot, $expensePlot]);
      $graph->Add($groupPlot);

      // Simpan gambar sementara
      $tempFile = tempnam(sys_get_temp_dir(), 'chart_').'.png';
      $graph->Stroke($tempFile);

      // Sisipkan ke worksheet
      $drawing = new Drawing();
      $drawing->setPath($tempFile);
      $drawing->setCoordinates('B' . $startRow);
      $drawing->setWidth($chartWidth);
      $drawing->setHeight(400);
      $drawing->setWorksheet($sheet);

      register_shutdown_function(function () use ($tempFile) {
        if (file_exists($tempFile)) unlink($tempFile);
      });
    }
  }