<!DOCTYPE html>
<html>
<head>
  <title>Ekspor Semua Data</title>
  <style>
    body {
      font-family: DejaVu Sans, sans-serif;
    }
    .metadata {
      margin-bottom: 20px;
    }
    .metadata p {
      margin: 0;
      font-size: 11px;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 10px;
      margin-bottom: 30px;
    }
    th, td {
      border: 1px solid #ddd;
      padding: 4px 5px;
      font-size: 10px;
    }
    th {
      background-color: #4F81BD;
      color: #fff;
      font-weight: bold;
      text-align: center;
      font-size: 11px;
    }
    .text-right {
      text-align: right;
    }
    .text-income {
      color: #28A745;
      font-weight: bold;
    }
    .text-expense {
      color: #DC3545;
      font-weight: bold;
    }
    .sub-row td {
      font-weight: bold;
      background: #D9E2F3;
      font-size: 11px;
    }
    .status-overspent {
      color: #DC3545;
      font-weight: bold;
    }
    .status-near-limit {
      color: #FFC107;
    }
    .status-on-track {
      color: #198754;
    }
  </style>
</head>
<body>
  <h3>Laporan Keuangan Lengkap</h3>

  @if(!empty($metadata))
  <div class="metadata">
    @foreach($metadata as $m)<p>
      {{ $m }}
    </p>
    @endforeach
  </div>
  @endif

  <h4>Transaksi</h4>
  @include('fintech::exports.tables._transactions_table', [
  'data'    => $allData['transactions'][0],
  'summary' => $allData['transactions'][1]
  ])

  <h4>Transfer</h4>
  @include('fintech::exports.tables._transfers_table', [
  'data'    => $allData['transfers'][0],
  'summary' => $allData['transfers'][1]
  ])

  <h4>Budget</h4>
  @include('fintech::exports.tables._budgets_table', [
  'data'    => $allData['budgets'][0],
  'summary' => $allData['budgets'][1]
  ])

  <div style="text-align:center; font-size:9px; color:#888; margin-top:20px;">
    Generated by VickyServer App - {{ now()->format('d M Y H:i') }}
  </div>
</body>
</html>