<!DOCTYPE html>
<html>
<head>
  <title>{{ $title }}</title>
  <style>
    body {
      font-family: DejaVu Sans, sans-serif;
    }
    .header-info {
      margin-bottom: 25px;
    }
    .header-info p {
      margin: 0;
      font-size: 11px;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 10px;
      table-layout: fixed;
    }
    th, td {
      border: 1px solid #ddd;
      padding: 6px 8px;
      font-size: 10px;
    }
    th {
      background-color: #4F81BD;
      color: #fff;
      font-weight: bold;
      text-align: center;
      font-size: 12px;
    }
    .text-right {
      text-align: right;
    }
    .status-overspent {
      color: #DC3545;
      font-weight: bold;
    }
    .status-near-limit {
      color: #FFC107;
    }
    .status-on-track {
      color: #198754;
    }
    .sub-row td {
      font-weight: bold;
      background: #D9E2F3;
      font-size: 11px;
    }
    .footer {
      text-align: center;
      font-size: 9px;
      color: #888;
      margin-top: 20px;
    }
    th:nth-child(1), td:nth-child(1) {
      width: 16%;
    }
    th:nth-child(2), td:nth-child(2) {
      width: 13%;
    }
    th:nth-child(3), td:nth-child(3) {
      width: 12%;
    }
    th:nth-child(4), td:nth-child(4) {
      width: 14%;
    }
    th:nth-child(5), td:nth-child(5) {
      width: 14%;
    }
    th:nth-child(6), td:nth-child(6) {
      width: 12%;
    }
    th:nth-child(7), td:nth-child(7) {
      width: 19%;
    }
  </style>
</head>
<body>
  <h3>{{ $title }}</h3>
  @if(!empty($summary['metadata']))
  <div class="header-info">
    @foreach($summary['metadata'] as $info)<p>
      {{ $info }}
    </p>
    @endforeach
  </div>
  @endif
  @include('fintech::exports.tables._budgets_table', ['data' => $data, 'summary' => $summary])

  <div class="footer">
    Generated by VickyServer App - {{ now()->format('d M Y H:i') }}
  </div>
</body>
</html>