<!DOCTYPE html>
<html>
<head>
  <title>{{ $title }}</title>
  <style>
    body {
      font-family: DejaVu Sans, sans-serif;
    }
    .header-info {
      margin-bottom: 25px;
    }
    .header-info p {
      margin: 0;
      font-size: 11px;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 10px;
      table-layout: fixed;
    }
    th, td {
      border: 1px solid #ddd;
      padding: 6px 8px;
      font-size: 10px;
    }
    th {
      background-color: #4F81BD;
      color: #fff;
      font-weight: bold;
      text-align: center;
      font-size: 12px;
    }
    .text-right {
      text-align: right;
    }
    .sub-row td {
      font-weight: bold;
      background: #D9E2F3;
      font-size: 11px;
    }
    .footer {
      text-align: center;
      font-size: 9px;
      color: #888;
      margin-top: 20px;
    }
    th:nth-child(1), td:nth-child(1) {
      width: 18%;
    }
    th:nth-child(2), td:nth-child(2) {
      width: 22%;
    }
    th:nth-child(3), td:nth-child(3) {
      width: 22%;
    }
    th:nth-child(4), td:nth-child(4) {
      width: 20%;
    }
    th:nth-child(5), td:nth-child(5) {
      width: 18%;
    }
  </style>
</head>
<body>
  <h3>{{ $title }}</h3>
  @if(!empty($summary['metadata']))
  <div class="header-info">
    @foreach($summary['metadata'] as $info)<p>
      {{ $info }}
    </p>
    @endforeach
  </div>
  @endif
  <table>
    <thead>
      <tr><th>Tanggal</th><th>Dari</th><th>Ke</th><th>Jumlah</th><th>Deskripsi</th></tr>
    </thead>
    <tbody>
      @php
      $symbol = $summary['symbol'] ?? 'Rp';
      $prec = $summary['precision'] ?? 0;
      $dec = $summary['decimal_mark'] ?? ',';
      $thou = $summary['thousands_separator'] ?? '.';
      $fmt = fn($v) => $symbol . ' ' . number_format($v, $prec, $dec, $thou);
      @endphp
      @foreach($data as $row)
      <tr>
        <td>{{ $row['Tanggal'] }}</td>
        <td>{{ $row['Dari'] }}</td>
        <td>{{ $row['Ke'] }}</td>
        <td class="text-right">{{ $row['Jumlah'] === '-' ? '0' : $row['Jumlah'] }}</td>
        <td>{{ $row['Deskripsi'] }}</td>
      </tr>
      @endforeach
      <tr class="sub-row">
        <td colspan="3">SUBTOTAL</td>
        <td class="text-right">{{ $fmt($summary['total']) }}</td>
        <td></td>
      </tr>
    </tbody>
  </table>
  <div class="footer">
    Generated by VickyServer App - {{ now()->format('d M Y H:i') }}
  </div>
</body>
</html>