<!DOCTYPE html>
<html>
<head>
  <title>{{ $title }}</title>
  <style>
    <style>
    body {
      font-family: DejaVu Sans, sans-serif;
    }
    .header-info {
      margin-bottom: 25px;
    }
    .header-info p {
      margin: 0;
      font-size: 11px;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 10px;
      table-layout: fixed;
      /* penting agar lebar kolom dihiraukan */
    }
    th, td {
      border: 1px solid #ddd;
      padding: 4px 5px;
      /* padding dikurangi */
      font-size: 10px;
      word-wrap: break-word;
    }
    th {
      background-color: #4F81BD;
      color: #fff;
      font-weight: bold;
      text-align: center;
      vertical-align: middle;
      font-size: 11px;
    }
    td {
      vertical-align: middle;
    }
    .text-right {
      text-align: right;
    }
    .text-income {
      color: #28A745;
      font-weight: bold;
    }
    .text-expense {
      color: #DC3545;
      font-weight: bold;
    }
    .sub-row td {
      font-weight: bold;
      background: #D9E2F3;
      font-size: 11px;
    }
    .footer {
      text-align: center;
      font-size: 9px;
      color: #888;
      margin-top: 20px;
    }

    /* Lebar kolom absolut */
    th:nth-child(1), td:nth-child(1) {
      width: 70px;
    }

    /* Tanggal */
    th:nth-child(2), td:nth-child(2) {
      width: 70px;
    }

    /* Tipe */
    th:nth-child(3), td:nth-child(3) {
      width: 90px;
    }

    /* Kategori */
    th:nth-child(4), td:nth-child(4) {
      width: 90px;
    }

    /* Dompet */
    th:nth-child(5), td:nth-child(5) {
      width: 80px;
    }

    /* Pemasukan */
    th:nth-child(6), td:nth-child(6) {
      width: 80px;
    }

    /* Pengeluaran */
    th:nth-child(7), td:nth-child(7) {
      width: auto;
    }

    /* Deskripsi (sisa) */
  </style>
</style>
</head>
<body>
<h3>{{ $title }}</h3>
@if(!empty($summary['metadata']))
<div class="header-info">
@foreach($summary['metadata'] as $info)<p>
{{ $info }}
</p>
@endforeach
</div>
@endif

<table>
<thead>
<tr>
<th rowspan="2">Tanggal</th>
<th rowspan="2">Tipe</th>
<th rowspan="2">Kategori</th>
<th rowspan="2">Dompet</th>
<th colspan="2">Amount</th>
<th rowspan="2">Deskripsi</th>
</tr>
<tr>
<th>Pemasukan</th>
<th>Pengeluaran</th>
</tr>
</thead>
<tbody>
@php
$symbol = $summary['symbol'] ?? 'Rp';
$prec = $summary['precision'] ?? 0;
$dec = $summary['decimal_mark'] ?? ',';
$thou = $summary['thousands_separator'] ?? '.';
$fmt = fn($v) => $symbol . ' ' . number_format($v, $prec, $dec, $thou);
@endphp
@foreach($data as $row)
<tr>
<td>{{ $row['Tanggal'] }}</td>
<td>{{ $row['Tipe'] }}</td>
<td>{{ $row['Kategori'] }}</td>
<td>{{ $row['Dompet'] }}</td>
<td class="text-right text-income">{{ $row['Pemasukan'] === '-' ? '0' : $row['Pemasukan'] }}</td>
<td class="text-right text-expense">{{ $row['Pengeluaran'] === '-' ? '0' : $row['Pengeluaran'] }}</td>
<td>{{ $row['Deskripsi'] }}</td>
</tr>
@endforeach
<tr class="sub-row">
<td colspan="4">SUBTOTAL</td>
<td class="text-right">{{ $fmt($summary['total_income']) }}</td>
<td class="text-right">{{ $fmt($summary['total_expense']) }}</td>
<td class="text-right">Net: {{ $fmt($summary['net']) }}</td>
</tr>
</tbody>
</table>

<div class="footer">
Generated by VickyServer App - {{ now()->format('d M Y H:i') }}
</div>
</body>
</html>