<!DOCTYPE html>
<html>
<head>
  <title>{{ $title }}</title>
  <style>
    body {
      font-family: Helvetica, Arial, sans-serif;
    }
    .header-info {
      margin-bottom: 25px;
    }
    .header-info p {
      margin: 0;
      font-size: 11px;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 10px;
    }
    th, td {
      border: 1px solid #ddd;
      padding: 4px 5px;
      /* padding dikurangi */
      font-size: 10px;
      word-wrap: break-word;
    }
    th {
      background-color: #4F81BD;
      color: #fff;
      font-weight: bold;
      text-align: center;
      vertical-align: middle;
      font-size: 11px;
    }
    td {
      vertical-align: middle;
    }
    .text-right {
      text-align: right;
    }
    .text-income {
      color: #28A745;
      font-weight: bold;
    }
    .text-expense {
      color: #DC3545;
      font-weight: bold;
    }
    .sub-row td {
      font-weight: bold;
      background: #D9E2F3;
      font-size: 11px;
    }
    .footer {
      text-align: center;
      font-size: 9px;
      color: #888;
      margin-top: 20px;
    }
  </style>
</head>
<body>
  <h3>{{ $title }}</h3>
  @if(isset($summary['metadata']) && count($summary['metadata']))
  <div class="header-info">
    @foreach($summary['metadata'] as $info)<p>
      {{ $info }}
    </p>
    @endforeach
  </div>
  @endif

  @include('fintech::exports.tables._transactions_table', ['data' => $data, 'summary' => $summary])

  <div class="footer">
    Generated by VickyServer App - {{ now()->format('d M Y H:i') }}
  </div>
</body>
</html>